Repository finos/SymphonyElectron, pull requests merged in 2018-03, with the labels that each got.

#309 ELECTRON-274: fix issue for diagnostics link
  js/windowMgr.js
Labels: bug, cla-signed

#303 Electron-308 (Fixes Spectron test cases)
  package.json
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/bringToFront.spectron.js
  tests/spectron/clipboard.spectron.js
  tests/spectron/close.spectron.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/minimize-on-close.spectron.js
  tests/spectron/notificationPosition.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronSetup.js
  tests/spectron/spellChecker.spectron.js
  tests/spectron/zoom-in-zoom-out.spectron.js
Labels: automation, bug, cla-signed

#313 ELECTRON-307 : add 32 bit windows installer support
  .gitignore
  installer/win/Symphony-x86.aip
Labels: cla-signed

#316 ELECTRON-340: upgrade electron to 1.8.3 and pin all the dependency versions
  package.json
Labels: cla-signed

#311 Electron-266 (Custom title bar for Windows 10)
  config/Symphony.config
  js/enums/api.js
  js/mainApiMgr.js
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
  js/utils/misc.js
  js/windowMgr.js
  js/windowsTitleBar/contents.js
  js/windowsTitleBar/index.js
  js/windowsTitleBar/style.css
Labels: cla-signed

#317 ELECTRON-293: remove notification limit of 5 and match it with screen size
  js/notify/electron-notify.js
Labels: cla-signed, enhancement, notifications

#314 Electron-318 (Included build number in the client version info)
  demo/index.html
  js/preload/preloadMain.js
  package.json
  tests/spectron/getVersionInfo.spectron.js
Labels: cla-signed

#321 ELECTRON-357 (Fix time-out issue in Unit tests and Spectron tests.)
  package.json
  tests/Search.test.js
  tests/SearchUtils.test.js
  tests/activityDetection.test.js
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/bringToFront.spectron.js
  tests/spectron/clipboard.spectron.js
  tests/spectron/close.spectron.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/getVersionInfo.spectron.js
  tests/spectron/minimize-on-close.spectron.js
  tests/spectron/notificationPosition.spectron.js
  tests/spectron/spectronSetup.js
  tests/spectron/spellChecker.spectron.js
  tests/spectron/zoom-in-zoom-out.spectron.js
Labels: cla-signed

#319 Electron 324: allow only https in pod url config during installation
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.pbxproj
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/mac/postinstall.sh
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-signed, enhancement, installer

#322 Electron 360: fix configuration property issues on 32 bit windows installer
  installer/win/Symphony-x86.aip
Labels: bug, cla-signed, installer

#320 Electron-338 (Replace html tags from message content)
  js/notify/notifyImpl.js
Labels: bug, cla-signed, security

#323 Electron 292: fix command line installer issues
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-signed

#307 SEARCH-598 and SEARCH-611 (Deleting data folder on Electron Crash)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/search/search.js
  js/search/searchConfig.js
  js/search/utils/search-launchd.js
  library/search-launch-agent.sh
  library/search-launch-daemon.sh
  package.json
  tests/Search.test.js
Labels: 18.5, cla-signed, enhancement, search

#315 SEARCH-621 (New exe for checking disk space)
  js/search/searchConfig.js
  js/search/searchUtils.js
  js/search/utils/checkDiskSpace.js
Labels: 18.5, cla-signed

#318 Electron-325 (Removed restriction from opening a popup from another popup window)
  demo/childWin.html
  demo/win.html
  js/windowMgr.js
  tests/spectron/popOuts.spectron.js
Labels: 18.5, cla-signed, enhancement

#324 ELECTRON-341: fix typo in the advanced installer config
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 18.5, bug, cla-signed

#325 Electron-336 (Update bring to front logic on Windows)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/bringToFront.js
  js/menus/menuTemplate.js
  js/windowMgr.js
  tests/spectron/bringToFront.spectron.js
Labels: cla-signed

#326 Electron-235 (Fix javascript error in notification)
  js/notify/electron-notify-preload.js
  js/notify/electron-notify.js
  js/notify/settings/configure-notification-position.js
Labels: cla-signed

#327 ELECTRON-371 (Unit test fix)
  tests/SearchUtils.test.js
Labels: cla-signed

#329 Electron 323: allow admins to set permissions to peripherals
  config/Symphony.config
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.h
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/mac/postinstall.sh
  installer/mac/symphony-mac-packager.pkgproj
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/windowMgr.js
Labels: cla-signed

#330 Electron-373 (Fix issue with closing screen picker modal)
  js/desktopCapturer/screen-picker.html
Labels: 18.5, bug, cla-signed

#328 ELECTRON-370: upgrade electron dependency to 1.8.4
  package.json
Labels: cla-signed

#331 ELECTRON-337: remove dev tools menu item
  js/menus/menuTemplate.js
  js/windowMgr.js
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/minimize-on-close.spectron.js
Labels: cla-signed
