Repository finos/SymphonyElectron, pull requests merged in 2018-04, with the labels that each got.

#332 ELECTRON-397: fix the regression on opening external urls
  js/windowMgr.js
Labels: cla-signed

#334 Electron-401 (fixes crash reporter)
  js/aboutApp/index.js
  js/aboutApp/renderer.js
  js/basicAuth/index.js
  js/basicAuth/renderer.js
  js/crashReporter.js
  js/desktopCapturer/index.js
  js/desktopCapturer/renderer.js
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
  js/utils/archiveHandler.js
  js/windowMgr.js
  package.json
Labels: 18.7, bug, cla-signed, do-not-merge

#336 Electron-409 (Fix generating crash report)
  js/utils/archiveHandler.js
  package.json
Labels: cla-signed

#312 SEARCH-627 & SEARCH-628 (Memory Indexing)
  demo/search.html
  js/preload/preloadMain.js
  js/search/search.js
  js/search/searchConfig.js
  js/search/searchLibrary.js
  tests/Search.test.js
Labels: cla-signed, do-not-merge, enhancement, search

#341 Electron-433 (Changes the logic for updating user config)
  installer/mac/postinstall.sh
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/config.js
  js/log.js
  js/main.js
  js/utils/compareSemVersions.js
  package.json
Labels: cla-signed

#343 ELECTRON-132: update icons for the app
  build/icon.icns
  build/icon.ico
Labels: cla-signed

#339 Electron-417 (Reposition active notifications whenever the config is updated)
  js/notify/electron-notify.js
  tests/spectron/notificationPosition.spectron.js
Labels: 18.8, bug, cla-signed, notifications

#346 Electron-391 (Redesigned Windows & macOS installer)
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.pbxproj
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/xcuserdata/vishwas.xcuserdatad/xcschemes/SymphonySettingsPlugin.xcscheme
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.h
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/mac/background.png
  installer/mac/intro.html
  installer/mac/postinstall.sh
  installer/mac/symphony-mac-packager.pkgproj
  installer/win/Assets/Banner.jpg
  installer/win/Assets/Banner.png
  installer/win/Assets/Tabloid.jpg
  installer/win/Assets/Tabloid.png
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: cla-signed

#347 Electron 385: add support for custom tlds
  config/Symphony.config
  js/utils/whitelistHandler.js
  js/windowMgr.js
Labels: cla-signed

#348 Electron-391 (Remove unwanted files in advanced installer)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-signed
