Repository finos/SymphonyElectron, pull requests merged in 2018-11, with the labels that each got.

#524 ELECTRON-906 (Fix copy image context menu)
  package.json
Labels: 18.23, :bug: bug, cla-present

#526 SEARCH-1059 (Electron - Swift search - A JavaScript error displays when the user reloads the Electron while the file .lz4 is creating)
  package.json
Labels: :mag: search, cla-present

#527 ELECTRON-932: change default pod url in installers
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Info.plist
  installer/mac/postinstall.sh
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 18.24, :sparkles: enhancement, GA, cla-present

#528 [R53] ELECTRON-879 (Bump Electron version to 4.0.0-beta.7)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/main.js
  js/mainApiMgr.js
  js/memoryMonitor.js
  js/preload/preloadMain.js
  package.json
Labels: cla-present
