Repository finos/SymphonyElectron, pull requests merged in 2018-07, with the labels that each got.

#417 ELECTRON-582: Upgrade electron framework to 2.0.3
  js/dialogs/showCertError.js
  js/main.js
  js/menus/menuTemplate.js
  js/notify/AnimationQueue.js
  js/notify/electron-notify.js
  js/notify/notifyImpl.js
  js/search/search.js
  js/utils/misc.js
  package.json
Labels: cla-present

#416 ELECTRON-538 (Fix the scrollbar issue on Windows)
  js/notify/settings/configure-notification-position.js
Labels: 18.13, bug, cla-present

#415 ELECTRON-445 (Change the memory refresh logic to auto-refresh after 4Hrs of user inactivity)
  js/memoryMonitor.js
  js/preload/preloadMain.js
Labels: 18.13, bug, cla-present

#418 ELECTRON-535 (Add missing screen snippet dependency files)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 18.14, bug, cla-present, installer

#420 ELECTRON-599: upgrade electron version to 2.0.4
  package.json
Labels: 18.13, cla-present, enhancement, upgrade

#390 ELECTRON-483 (Implement a functionality to display snack bar)
  js/enums/api.js
  js/mainApiMgr.js
  js/preload/preloadMain.js
  js/snackBar/content.js
  js/snackBar/index.js
  js/snackBar/style.css
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: cla-present, enhancement

#414 ELECTRON-485 (Add throttle of 1 sec for activate, bringToFront and setLocale to prevent DoS attacks)
  js/preload/preloadMain.js
  tests/spectron/resizeWindows.spectron.js
Labels: 18.13, cla-present

#419 ELECTRON-588 (Fix keyboard shortcut issue on Windows 10)
  js/windowMgr.js
Labels: 18.14, bug, cla-present

#423 ELECTRON-539 (Prevent multiple instance of notification configuration window)
  js/notify/settings/configure-notification-position.js
Labels: 18.14, bug, cla-present

#421 ELECTRON-512 (Create API only if the location.origin matches with whitelist or pod URL)
  js/enums/api.js
  js/mainApiMgr.js
  js/originCheck.js
  js/preload/preloadMain.js
  js/utils/whitelistHandler.js
Labels: 18.14, cla-present, security

#431 ELECTRON-492 (Disable screen share when media permissions are disabled)
  demo/index.html
  js/desktopCapturer/getSource.js
  js/desktopCapturer/getSources.js
  js/windowMgr.js
Labels: 18.14, bug, cla-present, rtc

#429 Revert "ELECTRON-512 (Create API only if the location.origin matches with whitelist or pod URL)"
  js/enums/api.js
  js/mainApiMgr.js
  js/originCheck.js
  js/preload/preloadMain.js
  js/utils/whitelistHandler.js
Labels: bug, cla-present, rc-branch, security

#428 Revert "ELECTRON-512 (Create API only if the location.origin matches with whitelist or pod URL)"
  js/enums/api.js
  js/mainApiMgr.js
  js/originCheck.js
  js/preload/preloadMain.js
  js/utils/whitelistHandler.js
Labels: bug, cla-present, security

#424 ELECTRON-378 (Focus the correct module with protocol actions)
  js/main.js
Labels: 18.14, bug, cla-present

#434 SEARCH-840 Migrates SwiftSearch to a different project
  DEV_SETUP.md
  demo/search.html
  js/compressionLib/index.js
  js/cryptoLib/crypto.js
  js/cryptoLib/index.js
  js/main.js
  js/preload/preloadMain.js
  js/search/queue.js
  js/search/search.js
  js/search/searchConfig.js
  js/search/searchLibrary.js
  js/search/searchUtils.js
  js/search/utils/checkDiskSpace.js
  js/search/utils/randomString.js
  js/search/utils/search-launchd.js
  js/windowMgr.js
  package.json
  tests/Search.test.js
  tests/SearchUtils.test.js
Labels: cla-present, do-not-merge, enhancement, search

#436 ELECTRON-618 (Initially register global shortcut)
  js/windowMgr.js
Labels: 18.4, bug, cla-present

#438 SEARCH-840 Updates searchApiVer and AIP
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/preload/preloadMain.js
  package.json
  tests/spectron/getVersionInfo.spectron.js
Labels: cla-present, search

#435 ELECTRON-505: add dev tools administration control
  config/Symphony.config
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.h
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/mac/postinstall.sh
  installer/mac/symphony-mac-packager.pkgproj
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/aboutApp/index.js
  js/basicAuth/index.js
  js/desktopCapturer/index.js
  js/notify/electron-notify.js
  js/notify/settings/configure-notification-position.js
  js/windowMgr.js
  locale/en-US.json
  locale/ja-JP.json
Labels: 18.14, cla-present, enhancement

#439 ELECTRON-593: add support to pass pod url through arguments
  js/main.js
Labels: 18.14, cla-present, enhancement

#442 Removes launchd plist files.
  library/search-launch-agent.sh
  library/search-launch-daemon.sh
Labels: cla-present, search

#441 Removes launchd plist files.
  library/search-launch-agent.sh
  library/search-launch-daemon.sh
Labels: cla-present, search

#430 AVT-914 [Spectron][Windows] Add test "Keep size and position of the windows in previous session"
  js/windowMgr.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/resizeWindows.spectron.js
  tests/spectron/saveLayout.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/zoom-in-zoom-out.spectron.js
Labels: cla-present
