Repository finos/SymphonyElectron, pull requests merged in 2018-05, with the labels that each got.

#338 Electron-414 (Add a logic not to close the notifications on mouse hover)
  js/notify/electron-notify-preload.js
  js/notify/electron-notify.js
Labels: 18.8, bug, cla-signed

#349 Electron 446: Disable setting custom downloads directory
  js/downloadManager/index.js
  js/menus/menuTemplate.js
  js/windowMgr.js
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/minimize-on-close.spectron.js
Labels: cla-signed

#350 Electron-385 (Remove third party dependency and write custom implementation)
  js/utils/whitelistHandler.js
  package.json
  tests/utils/whitelist.test.js
Labels: cla-signed

#351 ELECTRON-448: upgrade electron to 2.0.0 stable
  package.json
Labels: cla-signed

#352 Electron 451: add a new menu item "Symphony Help" under the help menu
  js/menus/menuTemplate.js
  tests/spectron/share-logs.spectron.js
Labels: cla-signed

#340 ELECTRON-430: Enable context isolation
  js/aboutApp/index.js
  js/basicAuth/index.js
  js/desktopCapturer/index.js
  js/notify/electron-notify.js
  js/notify/settings/configure-notification-position.js
  js/windowMgr.js
Labels: cla-signed, enhancement, security

#353 Electron-460 (Change the value of location and media checkboxes)
  installer/win/Symphony-x64.aip
Labels: cla-signed, enhancement, installer

#355 Revert "ELECTRON-430: Enable context isolation"
  js/aboutApp/index.js
  js/basicAuth/index.js
  js/desktopCapturer/index.js
  js/notify/electron-notify.js
  js/notify/settings/configure-notification-position.js
  js/windowMgr.js
Labels: cla-signed

#357 Electron-471 (Add URL validation dialog for the Windows installer)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: bug, cla-signed, installer

#359 Electron 455: fix memory leak with pop outs
  js/windowMgr.js
Labels: 18.9, bug, cla-signed

#361 Electron-470 (Add a new boolean check whether to activate main window)
  js/menus/menuTemplate.js
  js/screenSnippet/index.js
  js/windowMgr.js
Labels: 18.9, bug, cla-signed

#363 Electron 456
  js/main.js
  js/menus/menuTemplate.js
Labels: cla-signed

#364 ELECTRON-481: fix the error dialogs with always on top use case
  js/downloadManager/index.js
  js/main.js
  js/menus/menuTemplate.js
  js/windowMgr.js
Labels: cla-signed

#366 ELECTRON-136 (Disable auto reload feature for r51 release)
  js/mainApiMgr.js
  js/memoryMonitor.js
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
Labels: 18.9, cla-signed

#369 ELECTRON-459: fixes the issue in logo conflict in the about app window
  js/aboutApp/symphony-logo.png
Labels: cla-signed, enhancement

#370 ELECTRON-464 (Update Windows 10 title bar logo with a new logo)
  js/windowsTitleBar/contents.js
Labels: cla-signed, enhancement

#372 ELECTRON-500 / ELECTRON-384: fix protocol handler non-window use case
  js/main.js
  js/protocolHandler/index.js
Labels: 18.10, bug, cla-present

#368 ELECTRON-491 (Fixes a Javascript error when pop-in a meeting)
  js/windowMgr.js
Labels: 18.10, bug, cla-signed

#373 ELECTRON-453: add functionality to ignore cert transparency checks
  config/Symphony.config
  js/utils/whitelistHandler.js
  js/windowMgr.js
Labels: 18.10, cla-present, enhancement

#374 ELECTRON-513: upgrade electron framework to 2.0.1
  package.json
Labels: 18.10, cla-present, upgrade

#375 ELECTRON-479: fix launch on startup issue on first time launch
  js/main.js
Labels: 18.10, bug, cla-present, installer

#377 Electron-350 (Store/Restore maximized and fullscreen application state on launch)
  js/windowMgr.js
Labels: 18.10, cla-present, enhancement

#382 ELECTRON-525 (Hide cancel button in the Windows installer advance settings)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 18.10, bug, cla-present, installer

#383 ELECTRON-526: fix notification transparent window issue
  package.json
Labels: 18.10, bug, cla-present
