Repository finos/SymphonyElectron, pull requests merged in 2018-12, with the labels that each got.

#531 ELECTRON-825: fix typo in screen-sharing permissions message
  js/windowMgr.js
Labels: 18.24, :bug: bug, cla-present

#532 ELECTRON-899: add dev tools to menu & ELECTRON-905: read dev tools config dynamically
  js/config.js
  js/menus/menuTemplate.js
  js/windowMgr.js
Labels: 18.24, :sparkles: enhancement, cla-present, feature

#533 Change node-ffi base fork to symphonyoss
  package.json
Labels: cla-present

#537 ELECTRON-854 - error popup is not localized when network outage
  js/dialogs/showLoadError.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.24, :bug: bug, :flags: i18n, cla-present

#534 ELECTRON-955 - fixing toast notification does not show on top of the Electron after it is minimized and maximized again
  js/windowMgr.js
Labels: :bell: notifications, :bug: bug, :desktop_computer: Windows, cla-present

#530 ELECTRON-928 - Migrate Presence to the Power Monitor API
  js/activityDetection/index.js
  js/memoryMonitor.js
  js/preload/preloadMain.js
  package.json
  tests/__mocks__/electron.js
  tests/activityDetection.test.js
Labels: 18.24, :desktop_computer: Windows, cla-present
