Repository finos/SymphonyElectron, pull requests merged in 2018-08, with the labels that each got.

#437 AVT-937,AVT-938,AVT-939 : [Spectron][Windows] Close window when 'Minimize on Close' is ON
  tests/spectron/minimize-on-close-icon.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
Labels: automation, cla-present

#443 AVT-990 [Spectron][Windows] Add test "Verify Always on Top options when multiple applications are opened"
  tests/spectron/alwaysOnTopWithMultApps.spectron.js
  tests/spectron/saveLayout.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronUtils.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
Labels: automation, cla-present

#450 ELECTRON-661 (Security fix for pop-outs RCE)
  js/windowMgr.js
  package.json
Labels: 18.15, cla-present, security

#451 ELECTRON-607 (Change native menu bar style - Windows 10)
  js/enums/titleBarStyles.js
  js/mainApiMgr.js
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
  js/windowMgr.js
  js/windowsTitleBar/index.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.15, Windows, bug, cla-present, do-not-merge

#453 ELECTRON-652: add new app icons for windows and macOS
  build/icon.icns
  build/icon.ico
Labels: 18.15, cla-present, enhancement

#454 AVT-1024 Add test "Pop-up alert play depends on setting"
  package.json
  tests/spectron/saveLayout.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronUtils.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/toastNotification.spectron.js
Labels: cla-present

#455 ELECTRON-607 (Optimization and bug fix)
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
  js/windowMgr.js
Labels: 18.15, Windows, bug, cla-present

#447 AVT-1025: Verify toast notification when Persist Notification is ON
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/turnONPersistentToast.spectron.js
Labels: cla-present

#448 AVT-1031 AND AVT-1032: Verify toast notification for IMs, Signal,Room
  tests/spectron/spectronConstants.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/toastMouseHoveringForIM.spectron.js
  tests/spectron/turnONPersistentToast.spectron.js
Labels: cla-present

#457 ELECTRON-670 (Remove setting menu to null for pop-out)
  js/windowMgr.js
Labels: 18.15, Windows, bug, cla-present

#452 ELECTRON-600 (Implement Native Encryption for AESGCMEncrypt, AESGCMDecrypt & RSADecrypt)
  js/cryptoLib.js
  js/preload/preloadMain.js
  package.json
Labels: 18.15, cla-present, do-not-merge, enhancement

#456 [Spectron][MAC] Verify whether the main window can be minimized upto 300px
  tests/spectron/resizeWindows.spectron.js
  tests/spectron/spectronWindowsActions.js
Labels: automation, cla-present

#458 [AVT-1095] - [Spectron][MAC] Show 1 in tray icon when unread message = 1
  tests/spectron/badgeCount.spectron.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
Labels: automation, cla-present

#460 AVT-1081 [Spectron][Windows] pop-out chat, inbox
  tests/spectron/pop-Outs.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/toastMouseHoveringForIM.spectron.js
  tests/spectron/turnONPersistentToast.spectron.js
Labels: automation, cla-present

#462 SEARCH-905 (Electron "child_process" promisify issue)
  package.json
Labels: bug, cla-present, search, upgrade

#465 ELECTRON-665 (Localize custom title bar buttons for Windows 10)
  js/preload/preloadMain.js
  js/windowMgr.js
  js/windowsTitleBar/index.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.16, Windows, cla-present, i18n

#464 ELECTRON-648 (Prevent drag and drop of files)
  js/aboutApp/renderer.js
  js/desktopCapturer/renderer.js
  js/notify/electron-notify-preload.js
  js/notify/settings/configure-notification-position-preload.js
  js/windowMgr.js
Labels: 18.16, :bug: bug, cla-present

#466 AVT-1026 [Spectron][Windows] Configure alert position at top/bottom left/right
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/toastNotification.spectron.js
Labels: :robot: automation, cla-present

#463 AVT-1082 [Spectron][Windows] Pop-in popped-out chat
  tests/spectron/badgeCount.spectron.js
  tests/spectron/pop-Outs.spectron.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/toastMouseHoveringForIM.spectron.js
Labels: :robot: automation, cla-present

#468 ELECTRON-651 (Assign focused window to the screen picker) [Windows]
  js/desktopCapturer/index.js
  tests/__mocks__/electron.js
  tests/config.test.js
  tests/jest_unit.json
Labels: 18.16, :bug: bug, Windows, cla-present, rtc

#470 SEARCH-915 - Use N-API version of ffi to support Node > v10.0.0
  package.json
Labels: :mag: search, :sparkles: enhancement, cla-present

#471 ELECTRON-655: implement dynamic chrome command line flags logic
  js/main.js
Labels: 18.17, :sparkles: enhancement, cla-present

#472 ELECTRON-656 (Localize context menu labels)
  js/preload/preloadMain.js
  js/spellChecker/index.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.17, :bug: bug, cla-present, i18n

#473 SEARCH-915 - Revert back to ffi (ffi-napi - napi_get_uv_event_loop issue on Windows)
  js/cryptoLib.js
  package.json
Labels: :mag: search, cla-present, mirror

#474 SEARCH-915 - Revert back to ffi (ffi-napi - napi_get_uv_event_loop is…
  js/cryptoLib.js
  package.json
Labels: 18.6

#477 ELECTRON-669: add japanese localisation for download manager actions
  js/downloadManager/index.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.17, :sparkles: enhancement, cla-present, i18n

#469 ELECTRON-694 (Send activity only if network status is online)
  js/activityDetection/index.js
  js/windowMgr.js
Labels: 18.17, :bug: bug, cla-present

#475 ELECTRON-695 (master)- Fixing hover close button on notification
  js/notify/electron-notify-preload.js
  js/notify/electron-notify.js
Labels: 18.17, :bug: bug, cla-present, i18n

#480 ELECTRON-656 (Correct Japanese translations for context menu items)
  js/spellChecker/index.js
  js/utils/stringFormat.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.17, cla-present, i18n

#482 ELECTRON-647 - Fixing fullscreen mode disappears after reloading app
  js/preload/preloadMain.js
  js/windowsTitleBar/index.js
Labels: 18.17, :bug: bug, cla-present

#483 ELECTRON-729 - Accessibility color fix for customizing toast notifications
  js/notify/electron-notify-preload.js
Labels: 18.17, :no_entry: do-not-merge, :sparkles: enhancement, cla-present

#485 ELECTRON-685: upgrade electron framework version to 3.0.0-beta.8
  js/windowMgr.js
  package.json
Labels: 18.17, :bug: bug, cla-present

#484 ELECTRON-635 (Custom auto launch implementation)[Windows]
  config/Symphony.config
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/autoLaunch/index.js
  js/config.js
  js/main.js
  js/menus/menuTemplate.js
  js/windowsTitleBar/index.js
  tests/config.test.js
Labels: 18.17, :sparkles: enhancement, Windows, cla-present, installer

#486 ELECTRON-719 - Relaunch Application displays many times when selecting Native/ Custom
  js/menus/menuTemplate.js
Labels: 18.17, :bug: bug, :no_entry: do-not-merge, cla-present

#487 ELECTRON-718: localise the relaunch and cancel strings,
  js/menus/menuTemplate.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.17, :bug: bug, cla-present
