Repository finos/SymphonyElectron, pull requests merged in 2018-06, with the labels that each got.

#360 Electron-445 (Added a new API to keep electron in sync with client app user meeting status)
  js/enums/api.js
  js/mainApiMgr.js
  js/memoryMonitor.js
  js/preload/preloadMain.js
Labels: bug, cla-present, cla-signed

#380 SEARCH-766 (Rework "readFile" in Electron Preload Script)
  demo/search.html
  js/search/search.js
Labels: cla-present, search, security

#381 SEARCH-767 (Rework "path" in Electron Preload Script)
  js/search/searchUtils.js
  tests/SearchUtils.test.js
Labels: cla-present, search, security

#379 SEARCH-764-R52 (Rework "deleteIndexFolders" in the Electron Preload Script)
  js/search/search.js
  tests/spectron/getVersionInfo.spectron.js
Labels: cla-present, search, security

#386 SEARCH-775 (Enable Swift Search only if the version matches)
  demo/index.html
  js/preload/preloadMain.js
  tests/spectron/getVersionInfo.spectron.js
Labels: bug, cla-present, search

#384 ELECTRON-508 (Fix security issue with getSource and getSources)
  js/desktopCapturer/getSource.js
  js/desktopCapturer/getSources.js
Labels: 18.11, cla-present, security

#388 ELECTRON-508 (Change error and warn functions to prevent from exposing application path)
  demo/index.html
  js/screenSnippet/index.js
Labels: 18.11, cla-present, security

#389 Electron-486 (Add an option to configure Windows 10 title bar)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/config.js
  js/enums/titleBarStyles.js
  js/menus/menuTemplate.js
  js/preload/preloadMain.js
  js/windowMgr.js
  js/windowsTitleBar/contents.js
  js/windowsTitleBar/index.js
  js/windowsTitleBar/style.css
Labels: 18.11, bug, cla-present, enhancement

#394 ELECTRON-549: support not quitting app on mac upon closing window
  js/main.js
  js/windowMgr.js
Labels: 18.11, bug, cla-present

#393 ELECTRON-445 (Adds memory refresh menu item)
  js/menus/menuTemplate.js
Labels: 18.11, bug, cla-present

#391 SEARCH-767 (Rework "path" in Electron Preload Script)
  js/search/searchUtils.js
Labels: bug, cla-present, search, security

#397 Electron 549: fix main window show javascript error issues
  js/windowMgr.js
Labels: 18.11, bug, cla-present

#396 ELECTRON-530: add chrome flag to disable background timer throttling
  js/main.js
Labels: 18.12, cla-present, enhancement

#399 ELECTRON-563: fix main window close issue on macOS
  js/main.js
  js/windowMgr.js
Labels: 18.11, bug, cla-present, rc-branch

#398 ELECTRON-563: fix main window close issue on macOS
  js/main.js
  js/windowMgr.js
Labels: 18.11, bug, cla-present

#400 ELECTRON-568 (Enable applications tab only if it is passed in the types)
  js/desktopCapturer/getSource.js
  js/desktopCapturer/getSources.js
Labels: 18.12, bug, cla-present, rtc

#401 ELECTRON-519: support Japanese localization for menus, dialogs and windows
  .gitignore
  js/aboutApp/index.js
  js/basicAuth/basic-auth.html
  js/basicAuth/index.js
  js/basicAuth/renderer.js
  js/desktopCapturer/index.js
  js/desktopCapturer/renderer.js
  js/desktopCapturer/screen-picker.html
  js/dialogs/showCertError.js
  js/dialogs/showLoadError.js
  js/enums/api.js
  js/mainApiMgr.js
  js/menus/menuTemplate.js
  js/notify/settings/configure-notification-position-preload.js
  js/notify/settings/configure-notification-position.html
  js/notify/settings/configure-notification-position.js
  js/preload/preloadMain.js
  js/translation/i18n.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: 18.12, cla-present, enhancement

#406 ELECTRON-568 (Enable applications tab only if it is passed in the types)
  js/desktopCapturer/getSource.js
  js/desktopCapturer/getSources.js
Labels: 18.11, bug, cla-present, rc-branch, rtc

#407 ELECTRON-535 (Add support for screen snippet localization)
  js/screenSnippet/index.js
  js/translation/i18n.js
  package.json
Labels: 18.12, cla-present, enhancement

#409 ELECTRON-572 (Include missing screensnippet.exe for Windows x86)
  installer/win/Symphony-x86.aip
Labels: 18.11, bug, cla-present, installer, mirror

#408 ELECTRON-536: add missing translation strings
  js/translation/i18n.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: cla-present

#402 AVT-768 Add test "Verify whether the main window can be minimized upto 300px"
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/resizeWindows.spectron.js
  tests/spectron/spectronSetup.js
Labels: cla-present

#404 ELECTRON-540 - Add support for automatic selection of desktop capturer source
  js/desktopCapturer/getSource.js
  js/desktopCapturer/getSources.js
  js/windowMgr.js
Labels: 18.12, automation, cla-present, rtc

#413 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: cla-present

#405 Swift Search to Master
  demo/index.html
  demo/search.html
  js/preload/preloadMain.js
  js/search/search.js
  js/search/searchConfig.js
  js/search/searchLibrary.js
  js/search/searchUtils.js
  tests/Search.test.js
  tests/SearchUtils.test.js
  tests/spectron/getVersionInfo.spectron.js
Labels: cla-present, rc-branch, search

#412 ELECTRON-573 (Disable automatic detection of language and set system locale)
  js/spellChecker/index.js
Labels: bug, cla-present, rc-branch
