Repository finos/SymphonyElectron, pull requests merged in 2018-09, with the labels that each got.

#488 ELECTRON-730 (Implement aggressive refresh to optimize refresh)
  js/enums/api.js
  js/main.js
  js/mainApiMgr.js
  js/memoryMonitor.js
  js/preload/preloadMain.js
  js/windowMgr.js
Labels: :no_entry: do-not-merge, :running_man: 18.17, :sparkles: enhancement, cla-present

#490 ELECTRON-705 (Add custom title bar support for Window 7)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/menus/menuTemplate.js
  js/utils/misc.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: :computer: installer, :desktop_computer: Windows, :flags: i18n, :running_man: 18.17, :sparkles: enhancement, cla-present

#492 Upgrade electron-chromedriver version to 3.0.0-beta.1
  package.json
Labels: :robot: automation, cla-present

#493 AVT-1105 [Spectron][Mac] alwaysOnTop: Support the new test on MAC and remove the old test
  package.json
  tests/spectron/alwaysOnTop.spectron.js
  tests/spectron/alwaysOnTopWithMultApps.spectron.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronUtils.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
Labels: :robot: automation, cla-present

#495 Updated Timeout constants
  tests/spectron/spectronConstants.js
Labels: :robot: automation, cla-present

#489 ELECTRON-676 - Fixing Developer Tools window flashes before the popup
  js/windowMgr.js
Labels: :bug: bug, :running_man: 18.18, cla-present

#501 AVT-1155 [Spectron] Review and update the existing tests in spellChecker.spectron
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/spellChecker.spectron.js
Labels: :robot: automation, cla-present

#497 AVT-1141: Review and fix : AVT-1141,AVT-1142,AVT-1144
  tests/spectron/bringToFront.spectron.js
  tests/spectron/close.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
Labels: :robot: automation, cla-present

#499 AVT-1146 [Spectron] Review and update the existing tests in full-screen.spectron
  tests/spectron/full-screen.spectron.js
  tests/spectron/pop-Outs.spectron.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWindowsActions.js
Labels: :robot: automation, cla-present

#500 AVT-1147 [Spectron] Review and update the existing tests in getVersionInfo.spectron
  tests/spectron/getVersionInfo.spectron.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
Labels: :robot: automation, cla-present

#498 AVT-1145 [Spectron] Review and update the existing tests in closePopOutsOnReload.spectron
  tests/spectron/alwaysOnTopWithMultApps.spectron.js
  tests/spectron/badgeCount.spectron.js
  tests/spectron/closePopOutsOnReload.spectron.js
  tests/spectron/popOuts.spectron.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
Labels: :robot: automation, cla-present

#503 AVT-1152: fix and review AVT-1152,AVT-1149,AVT-1151,AVT-1156
  tests/spectron/clipboard.spectron.js
  tests/spectron/close.spectron.js
  tests/spectron/minimize-on-close-icon.spectron.js
  tests/spectron/minimize-on-close.spectron.js
  tests/spectron/notificationPosition.spectron.js
  tests/spectron/openACP.spectron.js
  tests/spectron/share-logs.spectron.js
  tests/spectron/spectronConstants.js
  tests/spectron/spectronInterfaces.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/toastFlashWhenOpenMultiApplication.spectron.js
  tests/spectron/toastMouseHoveringForIM.spectron.js
  tests/spectron/toastNotification.spectron.js
  tests/spectron/turnONPersistentToast.spectron.js
  tests/spectron/zoom-in-zoom-out.spectron.js
Labels: :robot: automation, cla-present

#491 ELECTRON-710 - Fix Always on top: notification does not show on top
  js/notify/electron-notify.js
Labels: :bug: bug, :no_entry: do-not-merge, :running_man: 18.18, cla-present

#504 Stabilize automation tests.
  tests/spectron/alwaysOnTopWithMultApps.spectron.js
  tests/spectron/closePopOutsOnReload.spectron.js
  tests/spectron/full-screen.spectron.js
  tests/spectron/getVersionInfo.spectron.js
  tests/spectron/minimize-on-close-icon.spectron.js
  tests/spectron/notificationPosition.spectron.js
  tests/spectron/openACP.spectron.js
  tests/spectron/pop-Outs.spectron.js
  tests/spectron/share-logs.spectron.js
  tests/spectron/spectronSetup.js
  tests/spectron/spectronWebActions.js
  tests/spectron/spectronWebDriver.js
  tests/spectron/spectronWindowsActions.js
  tests/spectron/spellChecker.spectron.js
  tests/spectron/toastFlashWhenOpenMultiApplication.spectron.js
  tests/spectron/toastMouseHoveringForIM.spectron.js
  tests/spectron/toastNotification.spectron.js
  tests/spectron/turnONPersistentToast.spectron.js
  tests/spectron/zoom-in-zoom-out.spectron.js
Labels: :robot: automation, cla-present

#506 ELECTRON-788: add clear cache functionality
  js/cacheHandler/index.js
  js/main.js
  js/menus/menuTemplate.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: :running_man: 18.19, :sparkles: enhancement, cla-present

#507 ELECTRON-795, ELECTRON-789: localise download manager messages
  js/downloadManager/index.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: :bug: bug, :running_man: 18.19, cla-present

#508 ELECTRON-790: add japanese localisation support for "Learn more" menu item
  js/menus/menuTemplate.js
  locale/en-US.json
  locale/en.json
  locale/ja-JP.json
  locale/ja.json
Labels: :bug: bug, :running_man: 18.19, cla-present

#505 ELECTRON-756 - About Symphony: Window shows at top-left corner after fullscreen
  js/aboutApp/index.js
Labels: :bug: bug, :desktop_computer: Windows, :running_man: 18.19, cla-present

#509 ELECTRON-758 (Change network request implementation to use electron's API)
  js/main.js
  js/mainApiMgr.js
  js/memoryMonitor.js
  js/preload/preloadMain.js
Labels: :running_man: 18.19, :sparkles: enhancement, cla-present

#510 ELECTRON-805: fix protocol handler uninstall issues on Windows
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/main.js
Labels: :bug: bug, :running_man: 18.19, cla-present
