Repository finos/SymphonyElectron, pull requests merged in 2019-08, with the labels that each got.

#755 fix: ELECTRON-1464 (Update custom title bar's title correctly)
  spec/windowsTitleBar.spec.ts
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, cla-present, master

#756 fix: ELECTRON-1464 (Update custom title bar's title correctly)
  spec/windowsTitleBar.spec.ts
  src/renderer/components/windows-title-bar.tsx
Labels: 3.8.x, :bug: bug, cla-present

#758 fix: ELECTRON-1459 (Update screen snippet image type to png from jpg)
  src/app/screen-snippet-handler.ts
Labels: :bug: bug, cla-present

#757 fix: ELECTRON-1459 (Update screen snippet image type to png from jpg)
  src/app/screen-snippet-handler.ts
Labels: 3.8.x, :bug: bug, cla-present

#760 fix: SEARCH-1646 - Include dictionary file and Update libraries for compressing the renderingBlob filed
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: :bug: bug, :mag: search, cla-present, master

#761 fix: ELECTRON-1465 (Persist locale changes to the user config file)
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/i18n.ts
Labels: :bug: bug, cla-present, master

#762 fix: ELECTRON-1465 (Persist locale changes to the user config file)
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/i18n.ts
Labels: 3.8.x, :bug: bug, cla-present

#763 feat: ELECTRON-1327 (Add/Remove 5.x Electron dependencies)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-present, master

#759 fix: SEARCH-1646 - Include dictionary file and Update libraries for compressing the renderingBlob filed
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: 3.8.x, :bug: bug, :mag: search, cla-present

#764 fix: ELECTRON-1321: support uppercase urls in windows installer
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, cla-present, master

#765 fix: ELECTRON-1171 (Sets font-family dynamically based on locale)
  spec/__snapshots__/basicAuth.spec.ts.snap
  src/renderer/components/basic-auth.tsx
  src/renderer/components/network-error.tsx
  src/renderer/styles/basic-auth.less
  src/renderer/styles/network-error.less
  src/renderer/styles/theme.less
Labels: :bug: bug, cla-present

#769 fix: ELECTRON-1482 (Update dependencies third-party dependencies)
  package.json
  src/app/config-handler.ts
  src/common/logger.ts
  src/common/whitelist-handler.ts
Labels: :shield: security, cla-present

#767 fix: Migrate to napi version of node-ffi/ref
  package.json
Labels: :mag: search, cla-present, master

#768 fix: ELECTRON-1482 (Update dependencies third-party dependencies)
  package.json
  src/app/config-handler.ts
  src/common/logger.ts
  src/common/whitelist-handler.ts
Labels: :bug: bug, :shield: security, cla-present

#770 feat: ELECTRON-1463: support linux build
  .gitignore
  build/background.tiff
  build/icon.icns
  build/icon.ico
  images/icon_1024.png
  package.json
  spec/appMenu.spec.ts
  spec/autoLaunchController.spec.ts
  spec/childWindowHandle.spec.ts
  spec/chromeFlags.spec.ts
  spec/protocolHandler.spec.ts
  spec/screenPicker.spec.ts
  spec/screenSharingIndicator.spec.ts
  src/app/app-menu.ts
  src/app/auto-launch-controller.ts
  src/app/config-handler.ts
  src/app/main.ts
  src/app/reports-handler.ts
  src/app/screen-snippet-handler.ts
  src/app/spell-check-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/env.ts
  src/common/logger.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/screen-picker.tsx
  src/renderer/notification-handler.ts
Labels: :sparkles: enhancement, cla-present

#772 fix: ELECTRON-1478: remove dev tools menu item via configuration
  src/app/app-menu.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present, master

#771 fix: ELECTRON-1389 (Fix snack bar issue on Windows & Fix RTC pop-out issue)
  package.json
  src/app/child-window-handler.ts
  src/app/window-actions.ts
  src/renderer/components/snack-bar.ts
  src/renderer/preload-main.ts
Labels: :bug: bug, cla-present

#773 fix: ELECTRON-1488 (Update i18n resources when page fail to load)
  src/app/window-handler.ts
  src/common/i18n.ts
  src/renderer/components/windows-title-bar.tsx
  src/renderer/preload-main.ts
Labels: :bug: bug, cla-present

#774 fix: ELECTRON-1505: add checks for url length
  src/app/child-window-handler.ts
  src/app/protocol-handler.ts
Labels: :bug: bug, cla-present

#776 fix: ELECTRON-1505 (Prevent opening links longer than 2083)
  src/app/child-window-handler.ts
  src/app/protocol-handler.ts
Labels: :bug: bug, :shield: security, cla-present, master

#775 fix: ELECTRON-1505 (Prevent opening links longer than 2083)
  src/app/child-window-handler.ts
Labels: 3.8.x, :bug: bug, :shield: security, cla-present
