Repository finos/SymphonyElectron, pull requests merged in 2019-12, with the labels that each got.

#820 fix: Fix Ctrl +, plus shortcut visible in menu's
  src/app/app-menu.ts
Labels: cla-present

#821 fix: SDA-1552 (Update new Symphony logo for notifications)
  src/renderer/assets/symphony-logo-black.png
  src/renderer/assets/symphony-logo-white.png
Labels: cla-present

#822 Make the zoomin to work
  src/app/app-menu.ts
Labels: cla-present

#817 feat: Implemented unified log extraction
  src/app/main-api-handler.ts
  src/app/reports-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: cla-present

#823 fix: Made the about dialog wider, to fit long SBE-names
  src/app/window-handler.ts
Labels: cla-present

#825 fix: Remove scroll if about windows fit, plus make it not resizable
  src/app/window-handler.ts
  src/renderer/styles/about-app.less
Labels: cla-present

#819 feat: SDA-1592 screen share indicator frame
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package-lock.json
  package.json
  src/app/window-handler.ts
Labels: cla-present

#826 fix: SDA-1620 (Access clipboard module via remote)
  src/renderer/components/about-app.tsx
Labels: :bug: bug, cla-present, master

#827 fix: https://perzoinc.atlassian.net/browse/SDA-1610
  src/app/window-handler.ts
Labels: cla-present

#828 fix: Check that source is not null before calling the screen frame applica…
  src/app/window-handler.ts
Labels: cla-present

#829 fix: Don't search for the main window use this.mainWindow, use getDisplayM…
  src/app/window-handler.ts
Labels: cla-present

#830 chore: SDA-1623: switch NodeJs dynamically during build
  scripts/build-linux.sh
  scripts/build-mac.sh
  scripts/build-win32.bat
  scripts/build-win64.bat
Labels: cla-present

#831 fix: New screen snippet tool
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package-lock.json
  package.json
  src/app/main-api-handler.ts
  src/app/screen-snippet-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/screen-snippet-bc-handler.ts
  src/renderer/ssf-api.ts
Labels: cla-present

#832 fix: SDA-1628: update installer plugin with latest SDK
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
Labels: cla-present

#835 fix: Bumped up version number
  package.json
Labels: cla-present

#834 fix: Added startup registry key removal to uninstall script
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-present

#836 fix: SDA-1636: revert auto layout settings
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
Labels: cla-present

#837 fix: Added removal of startup key 'electron.app.Symphony'
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: cla-present

#833 fix: SDA-1435 (Create API and logic to restart floater windows)
  src/app/app-menu.ts
  src/app/dialog-handler.ts
  src/app/spell-check-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present

#839 chore: SDA-1635: add snyk to builds
  package-lock.json
  scripts/build-linux.sh
  scripts/build-mac.sh
  scripts/build-win32.bat
  scripts/build-win64.bat
Labels: cla-present
