Repository finos/SymphonyElectron, pull requests merged in 2019-05, with the labels that each got.

#631 Typescript (Fix localization and custom title bar)
  demo/index.html
  spec/screenPicker.spec.ts
  src/app/app-menu.ts
  src/app/dialog-handler.ts
  src/app/spell-check-handler.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/screen-picker.tsx
  src/renderer/screen-snippet-bc-handler.ts
  src/renderer/ssf-api.ts
Labels: Typescript, cla-present

#634 ELECTRON-1170 (Fix Javascript errors and update spellchecker dict logic)
  dictionaries/en-AU.bdic
  dictionaries/en-CA.bdic
  dictionaries/en-GB.bdic
  dictionaries/en-US.bdic
  dictionaries/fr-FR.bdic
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/main.js
  js/notify/electron-notify.js
  js/spellChecker/index.js
  js/windowMgr.js
  package.json
Labels: 19.08, 3.x, :bug: bug, :no_entry: do-not-merge, cla-present

#633 ELECTRON-1117: remove node-auto-launch in favour of Electron API
  .travis.yml
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/autoLaunch/index.js
  js/main.js
  js/menus/menuTemplate.js
  package.json
Labels: 19.08, 3.x, :apple: MacOS, :desktop_computer: Windows, cla-present

#638 ELECTRON-1079: support custom path for user data & logging
  js/cacheHandler/index.js
  js/log.js
  js/main.js
  js/utils/getCmdLineArg.js
  package.json
Labels: 19.09, :bug: bug, cla-present

#636 ELECTRON-967 (Remove auto retry logic and add manual retry)
  js/enums/api.js
  js/mainApiMgr.js
  js/networkError/contents.js
  js/networkError/index.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
  package.json
Labels: 19.09, :sparkles: enhancement, cla-present

#639 ELECTRON-1208 (Add safety checks for did-finish-load events)
  js/windowMgr.js
Labels: 3.x, :bug: bug, cla-present

#640 ELECTRON-1215: more info window blank screen fix
  js/moreInfo/index.js
  js/moreInfo/renderer.js
Labels: 19.09, 3.x, :bug: bug, cla-present

#641 ELECTRON-1239 (Add safety check in electron-notify to prevent javascript errors)
  js/aboutApp/index.js
  js/basicAuth/index.js
  js/desktopCapturer/index.js
  js/moreInfo/index.js
  js/notify/electron-notify.js
  js/notify/settings/configure-notification-position.js
  js/screenSharingIndicator/index.js
Labels: 19.09, 3.x, cla-present

#642 ELECTRON-1239 (Add safety checks for logger)
  js/activityDetection/index.js
  js/badgeCount.js
  js/log.js
  js/memoryMonitor.js
  js/windowMgr.js
  tests/log.test.js
Labels: 19.09, 3.x, cla-present

#643 Typescript (Fix main window position calculation logic)
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#644 Typescript (Include missing supporting files for electron 3.x in .aip)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :desktop_computer: Windows, Typescript, cla-present

#647 Typescript (Change title-bar from className to id ) (ELECTRON-748)
  config/titleBarStyles.css
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  spec/appCacheHandler.spec.ts
  spec/appMenu.spec.ts
  src/app/app-cache-handler.ts
  src/app/child-window-handler.ts
  src/renderer/components/windows-title-bar.tsx
  src/renderer/styles/title-bar.less
Labels: :bug: bug, Typescript, cla-present

#645 SEARCH-1496 - Clear search_index folder before decompressing
  package.json
Labels: 3.x, :bug: bug, :mag: search, cla-present

#646 ELECTRON-988 (Remove registerAccelerator from menuItem options)
  js/menus/menuTemplate.js
Labels: 19.10, 3.x, :desktop_computer: Windows, cla-present

#651 ELECTRON-771 (Fix custom title bar button titles & localization)
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  spec/windowsTitleBar.spec.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, :desktop_computer: Windows, Typescript, localisation

#652 SEARCH-1466 - Data not tracking in user custom path
  package.json
Labels: 3.x, :bug: bug, :mag: search, cla-present

#649 ELECTRON-1247 (Remove old Symphony launch agent plist file)
  js/autoLaunch/index.js
  package.json
Labels: 19.10, :apple: MacOS, :bug: bug, cla-present

#650 ELECTRON-771 (Fix custom title bar button titles & localization)
  js/preload/preloadMain.js
  js/windowMgr.js
  js/windowsTitleBar/index.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 19.10, 3.x, :bug: bug, :desktop_computer: Windows, cla-present, localisation

#653 SEARCH-1466 - Data not tracking in user custom path
  package.json
Labels: :bug: bug, :mag: search, :trophy: master, cla-present

#655 Typescript (Fix custom user data path and menu items)
  package.json
  src/app/app-menu.ts
  src/app/config-handler.ts
  src/app/init.ts
Labels: :bug: bug, :trophy: master, Typescript, cla-present

#654 ELECTRON-1173: open browser tab for same host url
  src/app/child-window-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#656 ELECTRON-1213 (Fix localization for more information window)
  js/moreInfo/index.js
  js/moreInfo/more-info.html
  js/moreInfo/renderer.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 3.x, cla-present, localisation

#657 ELECTRON-1213 (Fix localization for more information window)
  src/app/window-utils.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/more-info.tsx
  src/renderer/preload-component.ts
Labels: :bug: bug, :trophy: master, Typescript, cla-present, localisation

#658 ELECTRON-1247 (Remove old Symphony launch agent plist file)
  package.json
  src/app/auto-launch-controller.ts
Labels: :bug: bug, :trophy: master, cla-present

#659 Set env path on app start child_process issue
  src/app/init.ts
Labels: :mag: search, :trophy: master, cla-present

#660 Typescript (Fix bound changes issue with main window)
  src/app/config-handler.ts
  src/app/window-actions.ts
Labels: :bug: bug, :trophy: master, Typescript, cla-present

#661 ELECTRON-1265 (Fix checks for handling links & pop-outs)
  js/windowMgr.js
Labels: 3.x, :bug: bug, blocker, cla-present

#662 ELECTRON-1265 (Fix checks for handling links & pop-outs)
  src/app/child-window-handler.ts
Labels: :bug: bug, :trophy: master, Typescript, blocker, cla-present

#665 SEARCH-1502 - Swift Search create search queries in SFE-client instead of Electron
  package.json
Labels: :mag: search, :sparkles: enhancement, cla-present

#664 SEARCH-1502 - Swift Search create search queries in SFE-client instead of Electron
  package.json
Labels: :mag: search, :sparkles: enhancement, :trophy: master, cla-present

#663 Typescript (Fix issues with setting the window origin)
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/desktop-capturer.ts
  src/renderer/preload-main.ts
Labels: :bug: bug, :trophy: master, Typescript, cla-present

#666 Typescript (Change network error logic and remove loading screen)
  spec/__snapshots__/loadingScreen.spec.ts.snap
  spec/loadingScreen.spec.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/download-manager.tsx
  src/renderer/components/network-error.tsx
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/styles/loading-screen.less
  src/renderer/styles/network-error.less
Labels: :sparkles: enhancement, :trophy: master, Typescript, cla-present, localisation
