Repository finos/SymphonyElectron, pull requests merged in 2019-09, with the labels that each got.

#777 feat: ELECTRON-1462 (Combine more information into about app window)
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/__snapshots__/moreInfo.spec.ts.snap
  spec/aboutApp.spec.ts
  spec/appMenu.spec.ts
  spec/moreInfo.spec.ts
  src/app/app-menu.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/about-app.tsx
  src/renderer/components/more-info.tsx
  src/renderer/preload-component.ts
  src/renderer/styles/about-app.less
  src/renderer/styles/more-info.less
Labels: :sparkles: enhancement, cla-present, master

#779 fix: SDA-1347 (Group multiple processes into a single task bar icon)
  src/app/init.ts
Labels: :bug: bug, cla-present, master

#778 fix: SDA-1347 (Group multiple processes into a single task bar icon)
  installer/mac/symphony-mac-packager.pkgproj
  scripts/build-mac.sh
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/__snapshots__/moreInfo.spec.ts.snap
  spec/aboutApp.spec.ts
  spec/appMenu.spec.ts
  spec/moreInfo.spec.ts
  src/app/app-menu.ts
  src/app/init.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/about-app.tsx
  src/renderer/components/more-info.tsx
  src/renderer/preload-component.ts
  src/renderer/styles/about-app.less
  src/renderer/styles/more-info.less
Labels: 6.x, :bug: bug, cla-present

#785 feat: Align NOTICE file to FINOS project blueprint
  NOTICE
Labels: cla-present

#784 chore: Align "Contributing" section in README.md to FINOS project blueprint
  README.md
Labels: cla-present

#786 fix: SDA-1526: remove support for opening non http(s) links
  spec/childWindowHandle.spec.ts
  src/app/child-window-handler.ts
Labels: :bug: bug, cla-present, master
