Repository finos/SymphonyElectron, pull requests merged in 2019-06, with the labels that each got.

#667 fix: Typescript (Change network error logic and remove loading screen)
  spec/__snapshots__/loadingScreen.spec.ts.snap
  spec/loadingScreen.spec.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/components/download-manager.tsx
  src/renderer/components/network-error.tsx
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/styles/loading-screen.less
  src/renderer/styles/network-error.less
Labels: :sparkles: enhancement, Typescript, cla-present

#668 feat: ELECTRON-1204 - add support for ttl
  gulpfile.js
  package.json
  spec/ttl-handler-spec.ts
  src/app/ttl-handler.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present, feature, target/5.x

#672 chore: aligning README.md and CONTRIBUTING.md to FINOS project blueprint language
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  NOTICE
  README.md
Labels: cla-present

#671 fix: Typescript (Fix throttle issue and update stats logs)
  spec/utils.spec.ts
  src/app/config-handler.ts
  src/app/init.ts
  src/app/stats.ts
  src/common/utils.ts
Labels: :trophy: master, Typescript, cla-present

#673 fix: ELECTRON-1022 (Fix issues with notification and origin)
  demo/index.html
  spec/mainApiHandler.spec.ts
  src/app/child-window-handler.ts
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-ssf-hendler.ts
  src/renderer/notification.ts
  src/renderer/ssf-api.ts
Labels: :bug: bug, :trophy: master, Typescript, cla-present

#678 fix: Typescript (Bump electron version to 3.1.11)
  package.json
Labels: :trophy: master, bump, cla-present

#669 feat: SEARCH-1514 - Include Index-Validator for verifying the index
  package.json
Labels: :mag: search, :sparkles: enhancement, :trophy: master, cla-present, target/5.x

#674 feat: SEARCH-1313 - Bump swift-search version from 3.0.0 to 1.55.2
  src/renderer/ssf-api.ts
Labels: :mag: search, :trophy: master, cla-present

#679 feat: ELECTRON-1297 (Add role alert to the notification container)
  src/renderer/components/notification-comp.tsx
Labels: :sparkles: enhancement, :trophy: master, cla-present

#681 revert: ffi and version changes
  package.json
  src/app/crypto-handler.ts
  src/renderer/ssf-api.ts
Labels: cla-present

#682 fix: Typescript (Fix issues with notification, menu & logger modules)
  demo/index.html
  spec/appMenu.spec.ts
  src/app/app-menu.ts
  src/app/window-actions.ts
  src/common/logger.ts
  src/renderer/notification-ssf-hendler.ts
Labels: :bell: notifications, :bug: bug, :desktop_computer: Windows, :trophy: master, Typescript, cla-present

#683 fix: ELECTRON-1306: update aip files to uninstall on scripts failure
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, :computer: installer, cla-present

#685 fix: ELECTRON-1169 (Increase screen sharing indicator to support Japanese chars)
  src/app/window-handler.ts
Labels: :trophy: master, Typescript, cla-present

#684 fix: ELECTRON-1177 (Update French translations for menu items)
  src/common/i18n-preload.ts
  src/common/i18n.ts
  src/locale/fr-FR.json
  src/locale/fr.json
  src/renderer/components/download-manager.tsx
Labels: :trophy: master, cla-present, localisation

#687 feat: Bump search API version to 1.55.3 to support from R55.3
  src/renderer/ssf-api.ts
Labels: :mag: search, :trophy: master, cla-present

#689 fix: ELECTRON-1264 (Fix ATS for localhost and update TLS version to 1.2)
  config/Symphony.config
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :shield: security, cla-present

#690 fix: ELECTRON-1310 L10N: Minimize on Close not localized in French
  src/locale/fr-FR.json
  src/locale/fr.json
Labels: :bug: bug, cla-present, localisation

#688 feat: SEARCH-1527 - Display swift-search version details in the More Info
  package.json
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/more-info.tsx
  src/renderer/ssf-api.ts
Labels: :mag: search, :sparkles: enhancement, cla-present

#686 fix: ELECTRON-1238 (Handle session permissions)
  src/app/child-window-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: :bug: bug, cla-present, localisation

#692 feat: SEARCH-1541 - Remove FreeDiskSpace to use node native binding
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: :mag: search, :sparkles: enhancement, cla-present

#691 feat: ELECTRON-1332 (Make Context Isolation configurable)
  config/Symphony.config
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :sparkles: enhancement, cla-present

#693 feat: ELECTRON-1292 (Unpack node binding files)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: :sparkles: enhancement, cla-present

#694 feat: SEARCH-1562 - Check Index File Size Before Initializing Swift Search
  package.json
Labels: :mag: search, :sparkles: enhancement, cla-present
