Repository finos/SymphonyElectron, pull requests merged in 2019-01, with the labels that each got.

#541 ELECTRON-839: add logic to set custom logs folder
  js/log.js
Labels: 18.26, :sparkles: enhancement, cla-present

#536 RTC-5104: screensharing indicator
  demo/index.html
  js/enums/api.js
  js/mainApiMgr.js
  js/preload/preloadMain.js
  js/screenSharingIndicator/index.js
  js/screenSharingIndicator/renderer.js
  js/screenSharingIndicator/screen-sharing-indicator.html
  js/screenSharingIndicator/showScreenSharingIndicator.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: cla-present

#543 ELECTRON-826 (Change the focusing logic for Window)
  js/windowMgr.js
Labels: 19.01, :bug: bug, :desktop_computer: Windows, cla-present

#544 ELECTRON-816: add checks for crash events when it is killed
  js/aboutApp/index.js
  js/basicAuth/index.js
  js/desktopCapturer/index.js
  js/moreInfo/index.js
  js/screenSharingIndicator/index.js
  js/windowMgr.js
Labels: 18.27, :bug: bug, :desktop_computer: Windows, cla-present

#542 ELECTRON-990 - add description to SSO checkbox in electron installer
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :apple: MacOS, :computer: installer, :desktop_computer: Windows, :sparkles: enhancement, cla-present

#545 ELECTRON-989: fix sso checkbox refresh
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 18.27, :bug: bug, :computer: installer, :desktop_computer: Windows, cla-present

#547 ELECTRON-869 (Enable spellchecker for main window)
  js/main.js
  js/mainApiMgr.js
  js/preload/preloadMain.js
  js/spellChecker/index.js
  js/windowMgr.js
Labels: 19.01, :bug: bug, cla-present

#546 ELECTRON-1003: fix menuitems with roles default
  js/menus/menuTemplate.js
Labels: :bug: bug, :desktop_computer: Windows, cla-present

#548 ELECTRON-903: fixing the notification text overflowing under user avatar
  js/notify/electron-notify.js
Labels: 19.01, :bug: bug, :desktop_computer: Windows, cla-present

#549 SEARCH-1243 (Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019)
  package.json
Labels: :apple: MacOS, :bug: bug, :mag: search, cla-present

#535 ELECTRON-956 - removing the minimize and maximize from the configure desktop alert position
  js/menus/menuTemplate.js
  js/windowMgr.js
Labels: :bug: bug, :desktop_computer: Windows, cla-present

#550 Revert "SEARCH-1243 (Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019)"
  package.json
Labels: cla-present

#551 SEARCH-1243 - Electron crashing after 54 pushed to corp on Thursday, Jan 10, 2019.
  package.json
Labels: :bug: bug, :mag: search, cla-present

#555 ELECTRON-992, ELECTRON-978: upgrade electron version to fix issues
  package.json
Labels: 19.02, :apple: MacOS, :arrow_up: upgrade, :bug: bug, cla-present

#553 ELECTRON-965 (Display warning dialog if certificate fails to verify Root CA or is not whitelisted)
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 19.01, :sparkles: enhancement, cla-present

#554 ELECTRON-1012: add localisation support for dev tools disabled message
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 19.02, :bug: bug, cla-present, localisation

#556 ELECTRON-769: removing context menu when right click on minimize, maximize and close button
  js/windowsTitleBar/index.js
Labels: 19.02, :bug: bug, :desktop_computer: Windows, cla-present

#557 ELECTRON-962: fix undesired javascript error
  js/notify/electron-notify.js
Labels: 19.02, :bell: notifications, :bug: bug, :desktop_computer: Windows, cla-present

#558 ELECTRON-1030: add localisation for about symphony window on Windows
  js/aboutApp/index.js
  js/aboutApp/renderer.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 19.02, :bug: bug, :desktop_computer: Windows, cla-present, localisation

#552 logger unit test
  jest.unit.config.json
  package.json
  spec/__mocks__/electron.ts
  spec/log.spec.ts
  src/common/logger.ts
Labels: cla-present, unit-test

#562 ELECTRON-965: revert the changes
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
  package.json
Labels: 19.02, :bug: bug, cla-present

#561 ELECTRON-965: revert the changes
  installer/mac/preinstall.sh
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
  package.json
Labels: 19.01, :bug: bug, cla-present

#564 ELECTRON-1051: fix localisation strings for download manager
  locale/ja-JP.json
  locale/ja.json
Labels: 19.02, :bug: bug, cla-present, localisation

#565 ELECTRON-1009: bump up version screen snippet
  package.json
Labels: 19.02, :bug: bug, cla-present
