Repository finos/SymphonyElectron, pull requests merged in 2019-03, with the labels that each got.

#575 fixing jest coverage output report
  jest.unit.config.json
Labels: cla-present, unit-test

#576 protocol handle unit test
  spec/protocolHandler.spec.ts
Labels: cla-present, unit-test

#578 ELECTRON-1050: fix issue where we were opening new window for same pod url
  js/log.js
  js/main.js
  js/mainApiMgr.js
  js/windowMgr.js
Labels: 19.05, 3.x, :bug: bug, cla-present

#577 ELECTRON-1050: fix issue where we were opening new window for same pod url
  js/windowMgr.js
Labels: 19.05, :bug: bug, cla-present

#579 Typescript download manager unit test
  jest.unit.config.json
  package.json
  spec/__snapshots__/downloadManager.spec.ts.snap
  spec/downloadManager.spec.ts
  spec/protocolHandler.spec.ts
  spec/setup/test-setup.js
  src/renderer/components/download-manager.tsx
Labels: cla-present, unit-test

#583 fixing Compiler error: Generic type ReactElement<P, T>
  package.json
Labels: cla-present, unit-test

#585 ELECTRON-1110 (Add power shell script to clean up Windows registry entries)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 19.05, 3.x, :bug: bug, :desktop_computer: Windows, cla-present

#584 ELECTRON-1110 (Add power shell script to clean up Windows registry entries)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 19.05, :bug: bug, :desktop_computer: Windows, cla-present

#580 fix app path on windows
  spec/__mocks__/electron.ts
Labels: cla-present, unit-test

#586 ELECTRON-1125: upgrade electron framework
  package.json
Labels: 19.05, :shield: security, cla-present

#589 ELECTRON-1129 (Fix first time launch config update logic)
  js/config.js
  js/main.js
Labels: 19.05, 3.x, :bug: bug, :desktop_computer: Windows

#590 ELECTRON-1129 (Fix first time launch config update logic)
  js/config.js
  js/main.js
Labels: 19.05, :bug: bug, :desktop_computer: Windows

#582 basic auth unit test
  spec/__snapshots__/basicAuth.spec.ts.snap
  spec/basicAuth.spec.ts
Labels: cla-present, unit-test

#587 screen picker unit test
  spec/__mocks__/electron.ts
  spec/__snapshots__/screenPicker.spec.ts.snap
  spec/__snapshots__/screenSharingIndicator.spec.ts.snap
  spec/downloadManager.spec.ts
  spec/screenPicker.spec.ts
  spec/screenSharingIndicator.spec.ts
Labels: cla-present, unit-test

#588 loading screen unit test
  spec/__snapshots__/loadingScreen.spec.ts.snap
  spec/loadingScreen.spec.ts
Labels: cla-present, unit-test

#592 ELECTRON-1132 (Remove HKU registry entry on uninstalling the SDA)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/config.js
  js/main.js
Labels: 19.05, :bug: bug, :desktop_computer: Windows, cla-present

#591 ELECTRON-1132 (Remove HKU registry entry on uninstalling the SDA)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  js/config.js
  js/main.js
Labels: 19.05, 3.x, :bug: bug, :desktop_computer: Windows, cla-present

#581 about app unit test
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/aboutApp.spec.ts
Labels: cla-present, unit-test

#593 ELECTRON-1131: changing extension from jpeg to png on windows
  js/screenSnippet/index.js
Labels: :bug: bug, :desktop_computer: Windows, cla-present

#595 ELECTRON-1131: changing extension from jpeg to png on windows
  js/screenSnippet/index.js
Labels: 3.x, :bug: bug, :desktop_computer: Windows, cla-present

#596 improving snapshot using snapshotSerializers to remove unnecessary things
  jest.unit.config.json
  package.json
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/__snapshots__/basicAuth.spec.ts.snap
  spec/__snapshots__/downloadManager.spec.ts.snap
  spec/__snapshots__/loadingScreen.spec.ts.snap
  spec/__snapshots__/screenPicker.spec.ts.snap
  spec/__snapshots__/screenSharingIndicator.spec.ts.snap
Labels: cla-present, unit-test

#598 Merge TS context isolation branch onto Typescript master branch
  demo/index.html
  gulpfile.js
  package.json
  spec/screenSharingIndicator.spec.ts
  src/app/activity-detection.ts
  src/app/app-cache-handler.ts
  src/app/auto-launch-controller.ts
  src/app/child-window-handler.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/crypto-handler.ts
  src/app/dialog-handler.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/protocol-handler.ts
  src/app/reports-handler.ts
  src/app/screen-snippet-handler.ts
  src/app/spell-check-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/animation-queue.ts
  src/common/api-interface.ts
  src/common/env.ts
  src/common/i18n-preload.ts
  src/common/i18n.ts
  src/common/logger.ts
  src/common/utils.ts
  src/renderer/app-bridge.ts
  src/renderer/assets/symphony-logo-black.png
  src/renderer/assets/symphony-logo-white.png
  src/renderer/components/about-app.tsx
  src/renderer/components/download-manager.tsx
  src/renderer/components/loading-screen.tsx
  src/renderer/components/more-info.tsx
  src/renderer/components/notification-comp.tsx
  src/renderer/components/screen-picker.tsx
  src/renderer/components/screen-sharing-indicator.tsx
  src/renderer/components/snack-bar.tsx
  src/renderer/desktop-capturer.ts
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
  src/renderer/styles/notification-comp.less
  src/renderer/styles/screen-sharing-indicator.less
  tsconfig.json
  tslint.json
Labels: cla-present

#601 ELECTRON-1138: support opening email composition in new window
  js/windowMgr.js
  package.json
Labels: 19.06, 3.x, :bug: bug, blocker, cla-present

#602 ELECTRON-1138: support opening email composition in new window
  js/windowMgr.js
  package.json
Labels: 19.06, :bug: bug, blocker, cla-present

#599 ELECTRON-967 (Handle network state and implement retry logic)
  js/enums/api.js
  js/mainApiMgr.js
  js/networkError/contents.js
  js/networkError/index.js
  js/networkError/style.css
  js/preload/preloadMain.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
  package.json
Labels: 19.06, 3.x, :sparkles: enhancement, cla-present

#600 ELECTRON-967 (Handle network state and implement retry logic)
  js/enums/api.js
  js/mainApiMgr.js
  js/networkError/contents.js
  js/networkError/index.js
  js/networkError/style.css
  js/preload/preloadMain.js
  js/windowMgr.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
  package.json
Labels: 19.06, :sparkles: enhancement, cla-present

#597 windows title bar unit test
  spec/__mocks__/electron.ts
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  spec/windowsTitleBar.spec.ts
Labels: cla-present, unit-test

#603 utils unit test
  spec/utils.spec.ts
  src/common/utils.ts
Labels: cla-present, unit-test

#605 ELECTRON-1141 (Display network error info screen only if SDA ends up in a blank screen)
  js/windowMgr.js
Labels: 3.x, :bug: bug, blocker, cla-present

#606 ELECTRON-1141 (Display network error info screen only if SDA ends up in a blank screen)
  js/windowMgr.js
Labels: 19.06, :bug: bug, blocker, cla-present

#604 app cache handler unit test
  spec/__mocks__/electron.ts
  spec/appCacheHandler.spec.ts
Labels: cla-present, unit-test

#607 app menu unit test
  spec/__mocks__/electron.ts
  spec/appMenu.spec.ts
  src/app/app-menu.ts
Labels: cla-present, unit-test

#611 Typescript (About app for Windows)
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/app-menu.ts
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
Labels: Typescript, cla-present

#608 Typescript autolaunch unittest
  spec/__mocks__/electron.ts
  spec/activityDetection.spec.ts
  spec/autoLaunchController.spec.ts
  spec/config.spec.ts
  spec/log.spec.ts
Labels: cla-present, unit-test

#609 Typescript (Complete notification & notification settings modules)
  demo/index.html
  js/notify/settings/configure-notification-position.html
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/components/notification-settings.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
  src/renderer/preload-component.ts
  src/renderer/ssf-api.ts
  src/renderer/styles/about-app.less
  src/renderer/styles/basic-auth.less
  src/renderer/styles/loading-screen.less
  src/renderer/styles/notification-comp.less
  src/renderer/styles/notification-settings.less
  src/renderer/styles/theme.less
  src/renderer/styles/title-bar.less
Labels: Typescript, cla-present

#610 child window handle unit test
  spec/__mocks__/electron.ts
  spec/childWindowHandle.spec.ts
Labels: cla-present, unit-test

#616 ELECTRON-1161 (3.x) : converting from png to jpg using jimp
  js/screenSnippet/index.js
  package.json
  tests/fixtures/snippet/snippet-base64.js
Labels: 3.x, :bug: bug, :desktop_computer: Windows, cla-present

#615 ELECTRON-1161: converting from png to jpg using jimp
  js/screenSnippet/index.js
  package.json
  tests/fixtures/snippet/snippet-base64.js
Labels: :bug: bug, :desktop_computer: Windows, cla-present

#619 SEARCH-1346 - Support new field renderingBlob Swift Search
  package.json
Labels: :bug: bug, :mag: search, cla-present

#620 Fix Localisation Issues
  js/desktopCapturer/renderer.js
  js/main.js
  js/moreInfo/index.js
  js/moreInfo/more-info.html
  js/moreInfo/renderer.js
  locale/en-US.json
  locale/en.json
  locale/fr-FR.json
  locale/fr.json
  locale/ja-JP.json
  locale/ja.json
Labels: 19.06, cla-present, localisation

#612 Typescript chromeflags unittest
  spec/__mocks__/electron.ts
  spec/childWindowHandle.spec.ts
  spec/chromeFlags.spec.ts
Labels: cla-present, unit-test

#621 ELECTRON-1100 (Add safety check for toggle developer tools)
  js/menus/menuTemplate.js
Labels: 3.x, :apple: MacOS, :bug: bug, cla-present

#622 ELECTRON-1100 (Add safety check for toggle developer tools)
  js/menus/menuTemplate.js
Labels: :apple: MacOS, :bug: bug, cla-present

#618 SEARCH-1346 - Support New Field for Indexing
  package.json
Labels: :bug: bug, :mag: search, :no_entry: do-not-merge, cla-present

#623 dialog handler unit test
  spec/__mocks__/electron.ts
  spec/dialogHandler.spec.ts
Labels: cla-present
