Repository finos/SymphonyElectron, pull requests merged in 2019-11, with the labels that each got.

#798 feat: SDA-1560 RTC: New screen sharing indicator
  spec/__snapshots__/screenSharingIndicator.spec.ts.snap
  spec/screenSharingIndicator.spec.ts
  src/app/window-handler.ts
  src/renderer/components/screen-sharing-indicator.tsx
  src/renderer/styles/screen-sharing-indicator.less
Labels: cla-present

#800 Show SFE version in about-window
  package.json
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/version-handler.ts
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
Labels: cla-present

#801 fix: SDA-1510 (Add margin-top dynamically for mana)
  src/renderer/components/windows-title-bar.tsx
  src/renderer/styles/title-bar.less
Labels: :bug: bug, cla-present, master

#802 fix: SDA-1581 (Set document title for all the window)
  src/renderer/preload-component.ts
Labels: 3.8.x, :bug: bug, blocker, cla-present

#803 fix: SDA-1581 (Set document title for all the window)
  src/renderer/preload-component.ts
Labels: :bug: bug, blocker, cla-present, master

#804 fix: SDA-1582 (Include missing .node files in AIP)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, cla-present, master

#807 fix: SDA-1588 (Add support for chromium sandbox mode)
  package.json
  src/app/init.ts
  src/app/window-utils.ts
Labels: 3.8.x, :bug: bug, blocker, cla-present

#805 feat: SDA-1553 Add screen-sharing-frame, for sharing screen
  src/app/window-handler.ts
  src/renderer/components/screen-sharing-frame.tsx
  src/renderer/preload-component.ts
  src/renderer/styles/screen-sharing-frame.less
Labels: cla-present

#808 fix: SDA-1498 L10N: "Press Esc to exit full screen" not localized
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#810 feat: SDA-1587 Broken functions in demo app
  docs/development/DEV_SETUP.md
  src/demo/README.md
  src/demo/index.html
  src/renderer/app-bridge.ts
Labels: cla-present

#811 SDA-1498 Update test for full screen for french & japanese
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#812 fix: SDA-1591 Translate the window title for notification settings
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/preload-component.ts
Labels: cla-present, localisation, rebuild-pull-request

#813 fix: INFOSEC-392 (Fix a security vulnerability with pupa an internal dependency of electron-dl)
  package.json
Labels: 3.8.x, :shield: security, bump, cla-present

#814 fix: SDA-48 (Port changes from 3.8.x & force sandbox for all BrowserWindow instances)
  package.json
  src/app/init.ts
  src/app/window-utils.ts
Labels: :shield: security, bump, cla-present, master

#816 We could not update Symphony on mac because the version was wrong
  installer/mac/preinstall.sh
Labels: cla-present

#815 fix: Add package-lock.json to git & disable protocol register for dev env
  .gitignore
  .travis.yml
  package-lock.json
  src/app/main.ts
Labels: :shield: security, :sparkles: enhancement, cla-present, master

#818 fix: Disable zoom of screen-picker
  src/app/window-handler.ts
Labels: cla-present
