Repository finos/SymphonyElectron, pull requests merged in 2019-10, with the labels that each got.

#787 feat: SDA-1525: add support for pod whitelisting
  config/Symphony.config
  docs/features/pod-whitelisting.md
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :shield: security, :sparkles: enhancement, cla-present, master

#788 fix: SDA-1531: add support for uppercase URLs in mac installer
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.pbxproj
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/xcuserdata/vishwas.xcuserdatad/xcschemes/SymphonySettingsPlugin.xcscheme
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
Labels: cla-present

#789 fix: SDA-1530 (Fix url validation check)
  package.json
  src/app/child-window-handler.ts
Labels: :bug: bug, bump, cla-present, master

#790 fix: SDA-1487: add support for creating custom log folders on the fly
  package.json
  src/common/logger.ts
Labels: :bug: bug, cla-present, master

#791 feat: Enable context isolation feature by default
  config/Symphony.config
Labels: :shield: security, cla-present, master

#792 fix: SDA-1549 (Prevent setting multiple intervals for activity detection)
  src/app/activity-detection.ts
Labels: :bug: bug, cla-present, master

#794 feat: SDA-1292: unpack all .node files in asar
  package.json
Labels: 3.8.x, :sparkles: enhancement, cla-present

#796 feat: SDA-1557: unpack asar DLL files locally
  package.json
Labels: :sparkles: enhancement, cla-present, master

#797 feat: SDA-1561: move app data to local profile
  spec/childWindowHandle.spec.ts
  src/app/reports-handler.ts
  src/common/logger.ts
Labels: 3.8.x, cla-present

#799 fix: SDA-1561 (Create app data directory manually)
  src/common/logger.ts
Labels: 3.8.x, :bug: bug, cla-present
