Repository finos/SymphonyElectron, pull requests merged in 2019-02, with the labels that each got.

#560 typescript: activityDetection unit test
  spec/__mocks__/electron.ts
  spec/activityDetection.spec.ts
Labels: cla-present, unit-test

#566 config unit test
  spec/__mocks__/electron.ts
  spec/config.spec.ts
Labels: cla-present, unit-test

#567 ELECTRON-1066, 1067: upgrade electron version
  js/windowMgr.js
  package.json
Labels: 19.03, :arrow_up: upgrade, :bug: bug, :shield: security, cla-present

#568 ELECTRON-1070: let electron handle protocol registration
  js/main.js
  package.json
Labels: 19.03, :bug: bug, :desktop_computer: Windows, cla-present

#569 ELECTRON-993: add pod url validation for installers
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.pbxproj
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Info.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 19.03, :apple: MacOS, :bug: bug, :desktop_computer: Windows, cla-present

#570 ELECTRON-802: ScreenSnippet improving capture quality
  package.json
Labels: 19.03, :desktop_computer: Windows, :sparkles: enhancement, cla-present

#572 SEARCH-1347 [Master] - Improve recency and relevance sort filter
  package.json
Labels: 19.03, :mag: search, :sparkles: enhancement, cla-present

#571 ELECTRON-1019: Enable spellchecker for popup window
  js/preload/preloadMain.js
  package.json
Labels: 19.03, :bug: bug, cla-present

#574 fixing indentation in preloadMain
  js/preload/preloadMain.js
Labels: cla-present
