Repository finos/SymphonyElectron, pull requests merged in 2019-04, with the labels that each got.

#617 Typescript (Fix issues and add support for BC)
  demo/download-manager.css
  demo/index.html
  package.json
  spec/__snapshots__/loadingScreen.spec.ts.snap
  spec/appMenu.spec.ts
  spec/downloadManager.spec.ts
  src/app/app-menu.ts
  src/app/auto-launch-controller.ts
  src/app/child-window-handler.ts
  src/app/config-handler.ts
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/common/i18n-preload.ts
  src/common/i18n.ts
  src/common/utils.ts
  src/common/whitelist-handler.ts
  src/renderer/app-bridge.ts
  src/renderer/components/download-manager.tsx
  src/renderer/components/loading-screen.tsx
  src/renderer/desktop-capturer.ts
  src/renderer/notification.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
  src/renderer/styles/loading-screen.less
  src/renderer/styles/theme.less
Labels: Typescript, cla-present

#626 Typescript (Fix spellchecker issue and bump electron version)
  demo/index.html
  package.json
  spec/mainApiHandler.spec.ts
  spec/protocolHandler.spec.ts
  src/app/app-menu.ts
  src/app/crypto-handler.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/protocol-handler.ts
  src/app/spell-check-handler.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/preload-main.ts
Labels: Typescript, cla-present

#627 Typescript (Added logic to clean up child windows)
  demo/index.html
  spec/utils.spec.ts
  src/app/main.ts
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/common/i18n-preload.ts
  src/common/i18n.ts
  src/common/utils.ts
  src/renderer/components/notification-settings.tsx
  src/renderer/desktop-capturer.ts
  src/renderer/notification.ts
  src/renderer/styles/snack-bar.less
Labels: Typescript, cla-present

#628 Typescript (Fix bound changes and update child window security)
  demo/index.html
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
  spec/childWindowHandle.spec.ts
  src/app/child-window-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/renderer/preload-main.ts
Labels: Typescript, cla-present

#630 mocking updateUserConfig on autoLaunchController unit test
  spec/autoLaunchController.spec.ts
Labels: Typescript, cla-present, unit-test

#629 Typescript (Optimize loading styles & register global shortcuts)
  demo/index.html
  demo/win.html
  spec/activityDetection.spec.ts
  src/app/activity-detection.ts
  src/app/app-menu.ts
  src/app/auto-launch-controller.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/memory-monitor.ts
  src/app/screen-snippet-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/animation-queue.ts
  src/common/api-interface.ts
  src/common/logger.ts
  src/renderer/app-bridge.ts
  src/renderer/components/windows-title-bar.tsx
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
  src/renderer/styles/snack-bar.less
Labels: Typescript, cla-present

#632 SEARCH-1428 (Complete workflow of context-isolation)
  package.json
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: :mag: search, Typescript, cla-present
