Repository finos/SymphonyElectron, pull requests merged in 2019-07, with the labels that each got.

#696 fix: ELECTRON-1243: fix chrome flags tests
  config/Symphony.config
  package.json
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/main.ts
  src/app/perf-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#695 feat: ELECTRON-1331 (Add new performance settings and add support for BI APIs)
  demo/index.html
  spec/chromeFlags.spec.ts
  src/app/analytics-handler.ts
  src/app/app-menu.ts
  src/app/chrome-flags.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present

#697 fix: ELECTRON-1278 (Bump up screen snippet version)
  package.json
Labels: :bug: bug, cla-present

#698 feat: SEARCH-1565 - Swift Search - ThreadAPI client interaction with throttling
  package.json
Labels: :mag: search, :sparkles: enhancement, cla-present

#700 fix: Add safety check for deleting real-time index (safety check)
  package.json
Labels: :mag: search, cla-present

#699 fix: ELECTRON-1227 (Add translations for permissions dialog)
  src/app/window-actions.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/desktop-capturer.ts
Labels: localisation

#701 fix: ELECTRON-1331 (Update the menu element text casing)
  src/app/analytics-handler.ts
  src/app/app-menu.ts
Labels: :sparkles: enhancement, cla-present

#702 fix: ELECTRON-1345: fix protocol handler action issues
  src/app/main.ts
  src/app/protocol-handler.ts
Labels: :bug: bug, cla-present

#704 fix: ELECTRON-1358 (Fix Multiple instance issue)
  src/app/init.ts
  src/app/main.ts
  src/app/spell-check-handler.ts
Labels: :bug: bug, cla-present

#703 feat: ELECTRON-1357: show version info from pod
  package.json
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/__snapshots__/moreInfo.spec.ts.snap
  spec/moreInfo.spec.ts
  src/app/main.ts
  src/app/version-handler.ts
  src/app/window-handler.ts
  src/common/logger.ts
  src/renderer/components/about-app.tsx
  src/renderer/components/more-info.tsx
Labels: :sparkles: enhancement, cla-present

#706 fix: Bump release version `1.55.3-rc.1`
  package.json
Labels: :mag: search, cla-present

#707 fix: ELECTRON-1338: fix download manager issues
  spec/downloadManager.spec.ts
  src/app/main.ts
  src/renderer/components/download-manager.tsx
Labels: :bug: bug, cla-present

#708 fix: ELECTRON-1037 (Disable context menu for notification windows)
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, cla-present

#709 fix: ELECTRON-1363 (Fix pop up menu position)
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#710 fix: ELECTRON-1364 (Fix issue with saving window state)
  src/app/window-actions.ts
Labels: :bug: bug, cla-present

#711 fix: ELECTRON-1365 & ELECTRON-1350 (fix issues with logo)
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  src/renderer/assets/symphony-title-bar-logo.png
  src/renderer/components/windows-title-bar.tsx
  src/renderer/styles/about-app.less
  src/renderer/styles/title-bar.less
Labels: :bug: bug, cla-present

#712 fix: ELECTRON-1367 (Fix always on top issue when relaunched)
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#713 fix: ELECTRON-1366 (Prevent javascript error related to screen module)
  src/app/main.ts
Labels: :bug: bug, cla-present

#715 fix: ELECTRON-1371 (Fix Custom title bar title margin issue)
  config/titleBarStyles.css
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  src/renderer/components/windows-title-bar.tsx
  src/renderer/styles/title-bar.less
Labels: :bug: bug, cla-present

#714 fix: ELECTRON-1364 (Optimize and fix window bounds update issue)
  src/app/config-handler.ts
  src/app/window-actions.ts
Labels: :bug: bug, cla-present

#716 fix: ELECTRON-1373: fix spacing in download manager
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/download-manager.tsx
Labels: cla-present

#717 fix: ELECTRON-1346 & ELECTRON-1370 (Fix notification text & background color)
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, cla-present

#718 fix: ELECTRON-1344 (Add logic to persist notification on mouse over)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present

#719 chore: ELECTRON-1362 (Bump electron version to 3.1.12 to fix notification crash issue)
  package.json
Labels: bump, cla-present

#720 fix: ELECTRON-1339 (Update DOM when ever custom title bar updates)
  src/renderer/components/windows-title-bar.tsx
Labels: cla-present

#722 fix: ELECTRON-1346 (Update notification text color to match previous version)
  src/renderer/components/notification-comp.tsx
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present

#724 fix: ELECTRON-1380 (Fix pop-up menu position for native title bar)
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#721 fix: ELECTRON-1369 (Set custom title bar's title once)
  src/renderer/components/windows-title-bar.tsx
Labels: cla-present

#723 fix: SEARCH-1582 - Fix sort order check
  package.json
Labels: :bug: bug, :mag: search, cla-present

#725 fix: ELECTRON-1381: fix localisation for file not found cases
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#726 fix: ELECTRON-1379: fix localisation for "Version" string
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
Labels: cla-present

#727 fix: ELECTRON-1382 (Fix notification z-index when alwaysOnTop is enabled)
  spec/dialogHandler.spec.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/renderer/notification.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present

#730 fix: ELECTRON-1392 (Add backward support for RTC v1 api)
  src/renderer/app-bridge.ts
Labels: :bug: bug, cla-present

#732 fix: ELECTRON-1380 (Show pop-up menu only on main window)
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/window-actions.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#728 fix: ELECTRON-1370 (Add default user profile picture)
  src/renderer/assets/symphony-default-profile-pic.png
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, cla-present

#733 fix: ELECTRON-1400: fix dev tools disabled localisation
  src/app/app-menu.ts
Labels: :bug: bug, cla-present

#731 revert: "fix: ELECTRON-1369 (Set custom title bar's title once)"
  src/renderer/components/windows-title-bar.tsx
Labels: cla-present

#729 fix: ELECTRON-1388: fix typo in notification setting radio button text
  src/renderer/components/notification-settings.tsx
Labels: :bug: bug, cla-present

#735 fix: ELECTRON-1394 (Add support for flashing notification)
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, :sparkles: enhancement, cla-present

#736 fix: ELECTRON-1406: fix issue in windows menu popping up for custom title bar
  src/app/window-actions.ts
Labels: :bug: bug, cla-present

#734 fix: ELECTRON-1346 (Fix notification fonts and safety checks for setAboutPanel)
  src/app/main.ts
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present

#737 fix: ELECTRON-1408: fix toggle dev tools menu item
  src/app/app-menu.ts
Labels: :bug: bug, cla-present

#738 fix: ELECTRON-1401 (Fix issues with pop-out window restore)
  src/app/child-window-handler.ts
  src/app/window-actions.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present

#739 fix: Bump index-version & Fix large index size (With libraries)
  package.json
Labels: :bug: bug, :mag: search, bump, cla-present

#740 fix: ELECTRON-1368 (Fix SnackBar & DownloadManager in pop-out)
  demo/index.html
  demo/win.html
  spec/__snapshots__/downloadManager.spec.ts.snap
  spec/__snapshots__/snackBar.spec.ts.snap
  spec/downloadManager.spec.ts
  spec/snackBar.spec.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/renderer/components/download-manager.ts
  src/renderer/components/download-manager.tsx
  src/renderer/components/snack-bar.ts
  src/renderer/components/snack-bar.tsx
  src/renderer/preload-main.ts
Labels: :bug: bug, cla-present

#741 fix: ELECTRON-1425 & ELECTRON-1405 - (Fix notification z-index & mouse hover issues)
  src/renderer/notification.ts
Labels: :bug: bug, cla-present

#742 fix: ELECTRON-1418 (Update permissions localization strings)
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present, localisation

#744 fix: ELECTRON-1396 & ELECTRON-1429 (Fix window constructor opts)
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#743 fix: ELECTRON-1431: add logic to update pod version dynamically
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/main.ts
  src/app/version-handler.ts
  src/app/window-handler.ts
Labels: cla-present

#745 fix: ELECTRON-1409 (Identify screens based on name instead of display_id for Windows)
  spec/screenPicker.spec.ts
  src/renderer/components/screen-picker.tsx
Labels: :bug: bug, cla-present

#746 wip: ELECTRON-1426: update assets to reflect new branding
  build/icon.icns
  build/icon.ico
  installer/mac/background.png
  installer/win/Assets/Banner.jpg
  installer/win/Assets/Banner.png
  installer/win/Assets/Tabloid.jpg
  installer/win/Assets/Tabloid.png
  src/renderer/assets/symphony-logo.png
Labels: :sparkles: enhancement, cla-present

#747 fix: SEARCH-1621 - Index Version in the config file gets updated immediately before lz4 file gets updated
  package.json
Labels: :bug: bug, :mag: search, cla-present

#748 fix: typo (Search API version displays as N/A)
  src/renderer/components/more-info.tsx
Labels: :bug: bug, cla-present

#749 fix: ELECTRON-1426 (Update custom title bar icon and fix Symphony icons)
  build/icon.icns
  build/icon.ico
  installer/mac/background.png
  package.json
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  src/renderer/components/windows-title-bar.tsx
Labels: :sparkles: enhancement, cla-present

#750 fix: ELECTRON-1445: fix minimise on close behaviour on macOS
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#751 fix: SEARCH-1627 - FreeDiskSpace check uses FREE instead of AVAILABLE
  package.json
Labels: :bug: bug, :mag: search, cla-present

#752 fix: ELECTRON-1451 (Fix notification flashing issue and logo in network error)
  src/renderer/components/network-error.tsx
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, cla-present

#753 docs: Fix assets extension
  docs/features/assets/Notification_screen.png
  docs/features/assets/screenshare.png
  docs/features/assets/selectApplication.png
  docs/features/assets/selectscreens.png
  docs/features/assets/snipping_tool.png
Labels: cla-present, documentation

#754 feat: ELECTRON-1327 (Bump Electron version to 5.x)
  package.json
  src/app/crypto-handler.ts
  src/app/memory-monitor.ts
  src/renderer/preload-main.ts
Labels: :sparkles: enhancement, bump, cla-present
