Repository finos/SymphonyElectron, pull requests merged in 2020-06, with the labels that each got.

#1006 fix: SDA-2022 Don't save snippet when annotation is aborted
  package.json
Labels: cla-present

#1007 fix: sda-2115 on windows the screen-share-indicator goes to background
  src/app/window-handler.ts
Labels: cla-present

#1008 feat: upgrade Electron to 9.x
  installer/win/Symphony-x64.aip
  package-lock.json
  package.json
  scripts/build-mac.sh
  src/app/download-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#1009 feat: SDA-2056: update welcome screen url to [POD].symphony.com
  spec/__snapshots__/welcome.spec.ts.snap
  src/app/window-handler.ts
  src/renderer/components/welcome.tsx
Labels: cla-present

#1010 fix: Do not persist the client switch, new parameter isMana
  src/app/config-handler.ts
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
Labels: cla-present

#1011 fix: SDA-2056: fix welcome screen button
  src/app/window-handler.ts
  src/renderer/components/welcome.tsx
Labels: cla-present

#1012 fix: Update to electron 9.0.2
  package.json
Labels: cla-present

#1013 fix: Disable certificate verification proxy
  src/app/child-window-handler.ts
Labels: cla-present

#1015 fix: SDA-2140: Screen share indicator does not close after reloading/closing SDA
  src/app/window-handler.ts
Labels: cla-present

#1016 fix: SDA-2137: Cannot close SDA when opening dev tool in separated window
  src/app/window-handler.ts
Labels: cla-present

#1017 fix: SDA-2142 Adding DPI awareness to fix border aligment
  package.json
Labels: cla-present

#1018 fix: sda-2140 forgot when screen share and than quiting sda
  src/app/window-handler.ts
Labels: cla-present

#1019 fix: SDA-2160 Parse and apply --windowSize command line argument
  src/app/window-handler.ts
Labels: cla-present

#1020 fix: SDA-2068: show welcome screen per installation
  config/InstallVariant.info
  installer/mac/postinstall.sh
  installer/win/Symphony-x64.aip
  package-lock.json
  package.json
  src/app/config-handler.ts
Labels: cla-present

#1021 fix: SDA-2193 (Update the CSS property as per the web client changes)
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, cla-present, mana

#1022 fix: SDA-2132: fix quitting app on uninstall
  installer/win/Symphony-x64.aip
Labels: cla-present

#1023 fix: SDA-2215: macos preference override
  src/app/main.ts
Labels: :bug: bug, cla-present

#1024 fix: SDA-2151: fix network request url reload
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#1025 fix: SDA-2179 Ensuring screen share indicator frame is turned off when switching client versions
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#1026 fix: SDA-2209 Applied consistent font styling
  installer/mac/intro.html
Labels: cla-present

#1027 fix: add gulp ts source root for building
  gulpfile.js
Labels: cla-present
