Repository finos/SymphonyElectron, pull requests merged in 2020-12, with the labels that each got.

#1127 fix: sda-2700 show 1.5/SFE 2.0/SFE-lite
  package.json
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/aboutApp.spec.ts
  spectron/about-app.spec.ts
  src/app/version-handler.ts
  src/renderer/components/about-app.tsx
Labels: cla-present

#1128 fix: SDA-2731: remove logic of deleting app cache on first install
  src/app/main.ts
Labels: :bug: bug, cla-present

#1129 fix: SDA-2731: remove logic of deleting app cache on install
  src/app/main.ts
Labels: 9.1.x, :bug: bug, cla-present

#1130 fix: SDA-2710 Fix broken image icon bug on windows
  package.json
  spec/snippingTool.spec.tsx
  src/app/screen-snippet-handler.ts
  src/renderer/components/snipping-tool.tsx
Labels: cla-present

#1131 fix: SDA-2533 Fixed double scroll bars on windows
  src/renderer/styles/snipping-tool.less
Labels: cla-present

#1132 feat: SDA-2650 Generate PDF with installation instruction
  installer/win/install_instructions_win.md
  scripts/jenkins-win64.bat
Labels: cla-present

#1133 feat: SDA-2571 Added correct BI events to screen annotate
  spec/annotateArea.spec.tsx
  spec/snippingTool.spec.tsx
  src/app/analytics-handler.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/snipping-tool.tsx
Labels: cla-present

#1134 fix: Make devTools enabled dependent on if dev environment
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#1136 fix: SDA-2747 Refactoring opening of snippet tool
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
Labels: cla-present

#1137 fix: SDA-2731: fix blank screen issue
  src/app/window-handler.ts
Labels: 9.1.x, :bug: bug, cla-present

#1138 fix: SDA-2731: reload app if stuck on white screen
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#1140 fix: Removed openDevTools
  src/app/window-handler.ts
Labels: cla-present

#1139 fix: Preview screen share
  src/app/window-handler.ts
  src/renderer/components/screen-picker.tsx
Labels: cla-present

#1141 fix: SDA-2745 Added support for APPDIR parameter
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/WelcomeDialog.cs
  installer/win/install_instructions_win.md
Labels: cla-present

#1142 fix: Revert "Changed API for getWindowOpts"
  src/app/window-handler.ts
Labels: cla-present

#1135 feat: SDA-2614 (Implement native electron notifications)
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/notifications/electron-notification.ts
  src/app/notifications/notification-helper.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: bump, cla-present, feature, master

#1143 fix: SDA-2764 Changed names of installer files
  scripts/jenkins-win64.bat
Labels: cla-present

#1145 fix: SDA-2762: load correct page on network issues
  docs/features/network-error.md
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present

#1147 fix: sda-2754, always quit red frame, and give the new red frame 300ms
  src/app/window-handler.ts
Labels: cla-present

#1149 chore: SDA-2793: move all build steps to the build scripts
  scripts/build-mac.sh
  scripts/build-win64.bat
  scripts/jenkins-win64.bat
Labels: :robot: automation, cla-present, documentation

#1150 chore: SDA-2793: move all build steps to the build scripts
  scripts/build-mac.sh
  scripts/build-win64.bat
Labels: 9.1.x, :robot: automation, cla-present, documentation

#1153 feat: SDA-2619 (implement reply feature for custom notification)
  docs/features/assets/custom_notifications.gif
  docs/features/assets/notifications_mac.png
  docs/features/assets/notifications_mac_2.png
  docs/features/notifications.md
  src/common/api-interface.ts
  src/demo/index.html
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/assets/notification-ext-badge.svg
  src/renderer/assets/notification-send-button-disabled.svg
  src/renderer/assets/notification-send-button-enabled.svg
  src/renderer/assets/notification-symphony-logo.svg
  src/renderer/assets/notification-thumbsup.svg
  src/renderer/components/notification-comp.tsx
  src/renderer/notification.ts
  src/renderer/styles/notification-comp.less
Labels: cla-present, feature

#1152 docs: generate release notes on build
  RELEASE_NOTES.md
  scripts/build-mac.sh
  scripts/build-win64.bat
Labels: cla-present

#1154 Update path to root
  scripts/build-win64.bat
Labels: cla-present

#1155 feat: SDA-2750 (update french replay translation)
  src/locale/fr-FR.json
  src/locale/fr.json
Labels: cla-present, localisation

#1156 fix: SDA-2769, SDA-2789, SDA-2790 Fixing scaling bug etc
  package.json
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/renderer/components/snipping-tool.tsx
Labels: cla-present

#1157 fix: SDA-2571 Fixed triggering multiple BI calls
  spec/annotateArea.spec.tsx
  spec/snippingTool.spec.tsx
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/renderer/components/snipping-tool.tsx
Labels: cla-present

#1158 ci: consolidate github actions
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/assign.yml
  .github/workflows/automerge.yml
  .github/workflows/jira-description.yml
  .github/workflows/review-reminder.yml
  .github/workflows/stats.yml
Labels: :robot: automation, cla-present, quality checks

#1161 fix: SDA-2811 (Fix css issue and make notification show as pop-up-menu)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification.ts
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present

#1162 fix: SDA-2806 (Fix notification inline reply focus issue with Windows)
  src/renderer/notification.ts
Labels: :bug: bug, cla-present, master

#1163 fix: SDA-2811 (Replace native electron notification with same tag)
  src/app/notifications/notification-helper.ts
Labels: :bug: bug, cla-present, master

#1164 feat: SDA-2775: Notification Position Window New UI
  spec/__snapshots__/notificationSettings.spec.ts.snap
  spec/notificationSettings.spec.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/components/notification-settings.tsx
  src/renderer/styles/notification-settings.less
Labels: cla-present, feature
