Repository finos/SymphonyElectron, pull requests merged in 2020-03, with the labels that each got.

#881 fix: Enabled window tracking for screen share indicator frame on mac
  package.json
  src/app/window-handler.ts
Labels: cla-present

#878 feat: SDA-1748 (Add support for Cloud Config)
  config/Symphony.config
  spec/appMenu.spec.ts
  spec/chromeFlags.spec.ts
  spec/config.spec.ts
  spec/mainApiHandler.spec.ts
  src/app/app-menu.ts
  src/app/auto-launch-controller.ts
  src/app/child-window-handler.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/config-utils.ts
  src/app/dialog-handler.ts
  src/app/main-api-handler.ts
  src/app/memory-monitor.ts
  src/app/perf-handler.ts
  src/app/screen-snippet-handler.ts
  src/app/version-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/common/utils.ts
  src/common/whitelist-handler.ts
  src/renderer/app-bridge.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present, cloud-config

#880 feat: SDA-1814 (Redesign about Symphony window)
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
  src/renderer/styles/about-app.less
Labels: :sparkles: enhancement, cla-present

#882 fix: SDA-1717: Screen sharing indicator is not removed when SDA is reloaded
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#883 fix: Let build script set app-version instead of hardcording
  installer/mac/preinstall.sh
Labels: cla-present

#884 fix: [SDA-1567] add menu item for disable gpu
  config/Symphony.config
  package-lock.json
  package.json
  spec/chromeFlags.spec.ts
  src/app/app-menu.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/config-utils.ts
  src/app/dialog-handler.ts
  src/app/stats.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#891 fix: SDA-1831 Don't show screen share indicator on taskbar
  src/app/window-handler.ts
Labels: cla-present

#893 fix: SDA-1778 (Load the complete pod url instead of hostname)
  src/app/window-utils.ts
Labels: :bug: bug, backport 6.1.0, cla-present

#896 fix: SDA-1839 Added ScreenShareIndicatorFrame.exe to installer for windows
  installer/win/Mana-x64.aip
  installer/win/Mana-x86.aip
Labels: cla-present

#897 fix: SDA-1836 Remove error logging when no error occured
  package.json
Labels: cla-present

#898 fix: SDA-1778 - Load the complete pod url instead of hostname
  src/app/window-utils.ts
Labels: 6.1.x, :bug: bug, cla-present

#895 feat: SDA-1838: upgrade electron framework to 8.x
  package-lock.json
  package.json
  spec/appCacheHandler.spec.ts
  spec/dialogHandler.spec.ts
  src/app/app-cache-handler.ts
  src/app/app-menu.ts
  src/app/dialog-handler.ts
  src/app/window-utils.ts
  src/common/logger.ts
  src/renderer/desktop-capturer.ts
Labels: cla-present

#899 fix: SDA-1847: fix french translation for restart dialog message
  src/locale/fr-FR.json
  src/locale/fr.json
Labels: cla-present

#900 fix: SDA-1841 Fixed misaligned frame
  package.json
Labels: cla-present

#902 fix: issues with whitelist
  package-lock.json
  package.json
  src/app/window-actions.ts
  src/app/window-utils.ts
Labels: cla-present

#903 fix: SDA-1847: fix French translations for GPU dialog
  src/locale/fr-FR.json
  src/locale/fr.json
Labels: cla-present

#904 fix: SDA-1858 (bump electron version to 6.1.9 from 6.1.5)
  package-lock.json
  package.json
Labels: bump, cla-present

#901 fix: SDA-1841 Fixed misaligned indicator frame
  package.json
Labels: cla-present

#908 fix: SDA-1866 (Filter out empty strings in cloud config)
  src/app/config-handler.ts
Labels: :bug: bug, blocker, cla-present, cloud-config, master

#909 fix: SDA-1866 (Filter out empty strings in cloud config)
  src/app/config-handler.ts
Labels: 6.1.x, :bug: bug, backport 6.1.x, blocker, cloud-config

#906 fix: SDA-1859 (Update the config logic & Hide menu items instead of disabling it)
  src/app/config-handler.ts
  src/app/config-utils.ts
Labels: 6.1.x, :bug: bug, :no_entry: do-not-merge, backport 6.1.x, cla-present, cloud-config

#910 fix: SDA-1863 Re-enable the --no-sandbox flag
  src/app/chrome-flags.ts
Labels: cla-present

#911 fix: SDA-1863 Re-enable the --no-sandbox flag
  package-lock.json
  package.json
  src/app/chrome-flags.ts
Labels: cla-present

#912 fix: SDA-1863 Re-enable the --no-sandbox flag
  src/app/chrome-flags.ts
Labels: cla-present

#905 fix: SDA-1859 (Update the config logic & Hide menu items instead of disabling it)
  src/app/config-handler.ts
  src/app/config-utils.ts
Labels: :bug: bug, cla-present, cloud-config, master

#913 fix: SDA-1857 (Add accelerator for zoom in for MacOS)
  src/app/app-menu.ts
Labels: 6.1.x, :bug: bug, cla-present

#914 fix: SDA-1857 (Add accelerator for zoom in for MacOS)
  package-lock.json
  src/app/app-menu.ts
Labels: :bug: bug, backport 6.1.x, cla-present, master

#916 fix: SDA-1859 (Update aip file for cloud config changes)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#915 fix: SDA-1859 (Update aip file for cloud config changes)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#918 fix: SDA-1859 & SDA-1857 (Add cloud config installer changes for MacOS & fix ZoomIn shortcut menu item)
  installer/mac/postinstall.sh
  src/app/app-menu.ts
  src/app/window-handler.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#917 fix: SDA-1859 & SDA-1857 (Add cloud config installer changes for MacOS & fix ZoomIn shortcut menu item)
  installer/mac/postinstall.sh
  src/app/app-menu.ts
  src/app/window-handler.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#920 fix: SDA-1859 (Support cloud config for silent installation) [Windows]
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#919 fix: SDA-1859 (Support cloud config for silent installation) [Windows]
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#921 fix: Merge master into mana and apply cloud-config fix into mana.aip
  installer/mac/postinstall.sh
  installer/win/Mana-x64.aip
  installer/win/Mana-x86.aip
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  src/app/app-menu.ts
  src/app/window-handler.ts
Labels: cla-present

#838 test: Spectron (Initial commit)
  .github/workflows/ci.yml
  .travis.yml
  appveyor.yml
  docs/development/DEV_SETUP.md
  package-lock.json
  package.json
  spectron/about-app.spec.ts
  spectron/fixtures/robot-actions.ts
  spectron/fixtures/spectron-setup.ts
  spectron/full-screen.spec.ts
  spectron/minimize.spec.ts
  spectron/notification.spec.ts
  spectron/screen-picker.spec.ts
  spectron/screen-sharing-indicator.spec.ts
  spectron/spell-checker.spec.ts
  src/app/init.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/demo/index.html
  src/renderer/notification.ts
  travis.yml
  tsconfig.spec.json
Labels: :robot: automation, Spectron, cla-present

#923 fix: SDA-1885 Javascript Error on cleaning logs
  src/common/logger.ts
Labels: :bug: bug, cla-present, master

#922 feat: SDA-1826 Add new check-media-permission
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: cla-present

#927 fix: SDA-1885 Javascript Error on cleaning logs
  src/common/logger.ts
Labels: 6.1.x, :bug: bug, cla-present

#924 fix: SDA-1880 & SDA-1882 (Fix background Throttling changes for cloud config)
  config/Symphony.config
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/perf-handler.ts
  src/app/window-handler.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#926 fix: SDA-1885 Javascript Error on cleaning logs
  src/common/logger.ts
Labels: 6.0.x, :bug: bug, cla-present

#929 fix: SDA-1884 (filter out empty arrays)
  src/app/config-handler.ts
  src/common/utils.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#928 fix: SDA-1884 (filter out empty arrays)
  src/app/config-handler.ts
  src/common/utils.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#925 fix: SDA-1880 & SDA-1882 (Fix background Throttling changes for cloud config)
  config/Symphony.config
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
  src/app/config-handler.ts
  src/app/perf-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#932 fix: SDA-1860: add flag to overwrite exe files upon installation
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 6.1.x, :bug: bug, backport 6.1.x, cla-present

#931 fix: SDA-1860: add flag to overwrite exe files upon installation
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: 6.0.x, :bug: bug, backport 6.0.x, cla-present

#930 fix: SDA-1860: add flag to overwrite exe files upon installation
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, cla-present, master

#933 fix: SDA-1893: upgrade electron to 6.1.9
  package.json
Labels: 6.0.x, :bug: bug, :shield: security, backport 6.0.x, cla-present

#934 fix: SDA-1890 (Fix auto launch on startup for cloud config)
  spec/autoLaunchController.spec.ts
  src/app/auto-launch-controller.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#935 fix: SDA-1890 (Fix auto launch on startup for cloud config)
  spec/autoLaunchController.spec.ts
  src/app/auto-launch-controller.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#937 fix: SDA-1897 Screen share indicator frame not showing on Mac
  src/app/window-handler.ts
Labels: cla-present

#936 fix: Sda 1899
  src/app/window-handler.ts
Labels: cla-present

#940 fix: SDA-1877 (Fix blank pop-out issue in 8.x electron version)
  package.json
  src/app/main.ts
Labels: :bug: bug, blocker, cla-present, master

#941 fix: SDA-1897 Cherry picked commits for fix from master
  src/app/window-handler.ts
Labels: cla-present

#939 fix: SDA-1268 (Workaround to exit fullscreen when notification is clicked)[RTC]
  src/renderer/notification.ts
  src/renderer/preload-main.ts
Labels: 6.1.x, :bug: bug, cla-present

#942 fix: SDA-1841 Fixing fullscreen issue on Mac
  package.json
Labels: cla-present

#943 fix: SDA-1841 Fixing fullscreen issue on Mac
  package.json
Labels: cla-present

#938 fix: SDA-1268 (Workaround to exit fullscreen when notification is clicked)[RTC]
  src/renderer/notification.ts
  src/renderer/preload-main.ts
Labels: :bug: bug, backport 6.1.x, cla-present, master

#947 fix: SDA-1910 (Add safety checks for devtools menu item)
  src/app/app-menu.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#946 fix: SDA-1910 (Add safety checks for devtools menu item)
  src/app/app-menu.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config

#945 fix: SDA-1895 (Escape backslash characters for autoLaunchPath)
  src/app/main-api-handler.ts
Labels: 6.1.x, :bug: bug, cla-present, cloud-config

#944 fix: SDA-1895 (Escape backslash characters for autoLaunchPath)
  src/app/main-api-handler.ts
Labels: :bug: bug, backport 6.1.x, cla-present, cloud-config, master

#948 fix: Add spectron test for zoom functionality
  spectron/fixtures/robot-actions.ts
  spectron/zoom.spec.ts
Labels: cla-present

#949 docs: Update Travis badge URL to master
  README.md
Labels: cla-present

#950 fix: SDA-1922: upgrade electron-dl dependency to 3.0.0
  package-lock.json
  package.json
Labels: :shield: security, cla-present, master

#952 fix: SDA-1904: disable network refresh on Mana
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, cla-present, master

#953 fix: Linux: (Install new packages to support latest SDA dependency)
  Dockerfile
Labels: cla-present

#956 fix: SDA-1929: upgrade packages related to mkdirp
  package-lock.json
  package.json
Labels: 6.1.x, :shield: security, cla-present

#957 fix: SDA-1929: fix vulnerable dependencies
  package-lock.json
  package.json
Labels: :shield: security, cla-present, master

#958 feat: SDA-1924 (Add new fields for about-app window and clipboard)
  spec/__mocks__/electron.ts
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/aboutApp.spec.ts
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
Labels: :sparkles: enhancement, cla-present, master

#959 feat: SDA-1932: persist client switch
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :sparkles: enhancement, cla-present, master
