Repository finos/SymphonyElectron, pull requests merged in 2020-04, with the labels that each got.

#954 fix: SDA-1927 Remove screen share indicator frame when quit SDA
  src/app/window-handler.ts
Labels: cla-present

#963 fix: SDA-1938: add csrf token to 1.5 switch
  src/app/window-handler.ts
Labels: :bug: bug, cla-present, master

#960 feat: Measure cpu
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: cla-present

#965 fix: SDA-1945: unregister global shortcuts for client switch on window blur
  src/app/window-handler.ts
Labels: cla-present

#966 chore: SDA-1942: skip setting expiry if value is 0
  gulpfile.js
Labels: :sparkles: enhancement, cla-present

#967 fix: SDA-1948: write snippet image to user data directory temp folder
  src/app/screen-snippet-handler.ts
Labels: :bug: bug, cla-present

#968 feat: SDA-1699 (Initial SDA - Mana extension bridge implementation)
  src/renderer/preload-main.ts
Labels: cla-present, mana, master

#969 fix: SDA-1901 - Add swift-search related .node files
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
Labels: :bug: bug, :mag: search, cla-present

#970 fix: SDA-1951 Added version and product info to ScreenShareIndicatorFrame and ScreenSnippet
  package.json
Labels: cla-present

#972 feat: SDA-1062: warn users before closing running app
  installer/mac/preinstall.sh
  installer/mac/symphony-mac-packager.pkgproj
Labels: :sparkles: enhancement, cla-present

#974 feat: SDA-1062: warn users before closing running app (windows)
  installer/win/Symphony-x64.aip
  installer/win/Symphony-x86.aip
  package.json
Labels: :sparkles: enhancement, cla-present

#977 feat: SDA-1983: implement simplified installer window on SDA
  config/Symphony.config
  package-lock.json
  spec/__snapshots__/welcome.spec.ts.snap
  spec/welcome.spec.ts
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/assets/symphony-logo-plain.png
  src/renderer/components/welcome.tsx
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/styles/welcome.less
Labels: :sparkles: enhancement, cla-present

#973 feat: SDA-1818: simplify macOS installer
  installer/mac/README.md
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Info.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/MacOS/SymphonySettingsPlugin
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/Base.lproj/MyInstallerPane.nib
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/InstallerSections.plist
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/en.lproj/InfoPlist.strings
  installer/mac/SymphonySettingsPlugin.bundle/Contents/Resources/en.lproj/Localizable.strings
  installer/mac/SymphonySettingsPlugin.bundle/Contents/_CodeSignature/CodeResources
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.pbxproj
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/xcuserdata/vishwas.xcuserdatad/xcschemes/SymphonySettingsPlugin.xcscheme
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin.xcodeproj/xcuserdata/vishwas.xcuserdatad/xcschemes/xcschememanagement.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Base.lproj/MyInstallerPane.xib
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/Info.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/InstallerSections.plist
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.h
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/MyInstallerPane.m
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/en.lproj/InfoPlist.strings
  installer/mac/SymphonySettingsPlugin/SymphonySettingsPlugin/en.lproj/Localizable.strings
  installer/mac/postinstall.sh
  installer/mac/symphony-mac-packager.pkgproj
  package.json
  scripts/build-mac.sh
Labels: :sparkles: enhancement, cla-present

#978 feat: SDA-1959 Removed dialogs from windows installer
  installer/win/Symphony-x64.aip
Labels: cla-present

#979 fix: tweaked PermissionRequestHandler to resolve correctly on macOS
  src/app/window-actions.ts
Labels: cla-present

#981 fix: SDA-2013: fix origin check for simplified installer
  src/app/child-window-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present
