Repository finos/SymphonyElectron, pull requests merged in 2020-01, with the labels that each got.

#840 fix: SDA-1546 (Update SDA Icons)
  images/icon.icns
  images/icon.ico
  spec/__snapshots__/aboutApp.spec.ts.snap
Labels: :sparkles: enhancement, cla-present, master

#841 fix: SDA-1648 (Fix mouse leave events on notification window)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification.ts
Labels: :bug: bug, cla-present, master

#842 fix: SDA-1651 (Temporarily disable AOT when screen snippet is open)
  spec/appMenu.spec.ts
  src/app/app-menu.ts
  src/app/screen-snippet-handler.ts
  src/app/window-actions.ts
Labels: :bug: bug, cla-present, master

#843 fix: SDA-1661 (Make about app window a modal window)
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present, master

#844 fix: SDA-1657 Maximized SDA saves co-ordinates
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
Labels: :no_entry: do-not-merge, cla-present

#845 fix: Update screen snippet
  package.json
Labels: cla-present

#846 fix: Updated screen snippet version
  package.json
Labels: cla-present

#847 fix: SDA-1284 (Add logic to close screen snippet tool)
  src/app/screen-snippet-handler.ts
  src/renderer/ssf-api.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present, master

#848 fix: SDA-1665 (Set level to modal-panel when in fullscreen)
  src/app/window-actions.ts
Labels: :bug: bug, cla-present, master

#850 fix: SDA-1668: add entitlements for macOS catalina
  entitlements.mac.plist
  package.json
Labels: cla-present

#849 fix: SDA-1668: add entitlements for macOS catalina
  entitlements.mac.plist
  package.json
Labels: cla-present

#851 fix: SDA-1673 Bumping version number for screen snippet tool
  package.json
Labels: cla-present

#853 fix: SDA-1704 (Make Screen sharing indicator window closable)
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#852 fix: SDA-1704 (Make screen sharing indicator window closable)
  src/app/window-handler.ts
Labels: :bug: bug, backport 6.0.x, cla-present

#854 fix: Changing the product id to allow co-existance with 1.5
  installer/win/Mana-x64.aip
  installer/win/Mana-x86.aip
Labels: cla-present

#857 fix: SDA-1708 Move screen-sharing indicator to the same screen as Symphony…
  src/app/window-handler.ts
Labels: cla-present

#859 fix: SDA-1500 (Fix incorrect style formatting)
  src/renderer/components/download-manager.ts
Labels: :bug: bug, cla-present

#856 fix: SDA-1666 (Make screen sharing indicator window focusable)
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#858 fix: SDA-1395 (Disable context menu for action buttons)
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, cla-present

#860 fix: SDA-1716 (Fix issues with source name case-sensitivity)
  src/renderer/components/screen-picker.tsx
Labels: :bug: bug, backport 6.0.x, cla-present

#861 fix: SDA-1716 (Fix issues with source name case-sensitivity)
  src/renderer/components/screen-picker.tsx
Labels: :bug: bug, cla-present

#862 fix: Update Symphony.config
  config/Symphony.config
Labels: backport 6.0.x, cla-present

#864 build: Complete docker setup for generating Linux builds
  .dockerignore
  Dockerfile
  docs/development/DEV_SETUP.md
  package-lock.json
  package.json
  src/app/app-menu.ts
  src/common/logger.ts
Labels: :sparkles: enhancement, cla-present, documentation

#866 fix: sda-1720 windows/electron BrowserWindow does not always open a window…
  src/app/window-handler.ts
Labels: cla-present
