Repository finos/SymphonyElectron, pull requests merged in 2020-10, with the labels that each got.

#1082 fix: SDA-2421: copy config on startup
  src/app/config-handler.ts
  src/app/main.ts
Labels: :bug: bug, master

#1084 chore: update setup guide
  README.md
  docs/development/DEV_SETUP.md
Labels: cla-present, documentation

#1086 fix: SDA-2476 Handling user having swapped left/right mouse buttons
  package.json
Labels: cla-present

#1090 fix: SDA-2171 Fix for screen snippet offset on windows 7
  package.json
Labels: cla-present

#1089 fix: SDA-2524, SDA-2525: upgrade electron to 9.3.2
  package.json
Labels: :shield: security, cla-present

#1088 fix: SDA-2524, SDA-2525: upgrade electron to 9.3.2
  package.json
Labels: :shield: security, cla-present

#1085 chore: add new actions for PRs
  .github/minimum-reviews.yml
  .github/workflows/action.yml
  .github/workflows/automerge.yml
Labels: cla-present, documentation

#1093 fix: SDA-2516 Extract programs folder location into property
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/WelcomeDlg.cs
Labels: cla-present

#1091 feat: SDA-2559: clean app cache on install & crash
  package.json
  spec/appCacheHandler.spec.ts
  src/app/app-cache-handler.ts
  src/app/dialog-handler.ts
  src/app/main.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: :sparkles: enhancement, cla-present

#1092 feat: SDA-2559: clean app cache on install
  package.json
  spec/appCacheHandler.spec.ts
  src/app/app-cache-handler.ts
  src/app/dialog-handler.ts
  src/app/main.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: 9.1.x, :sparkles: enhancement, cla-present

#1094 fix: SDA-2516 Added missing 'Symphony' to paths
  installer/win/WixSharpInstaller/WelcomeDlg.cs
Labels: cla-present

#1096 fix: SDA-2511 Making back button work from InstallDir screen
  installer/win/WixSharpInstaller/CloseDlg.cs
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/WelcomeDlg.cs
Labels: cla-present

#1099 fix: SDA-2526 Display uninstall confirmation dialog
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1097 fix: SDA-2559: Delete app cache on Install
  spec/appCacheHandler.spec.ts
  src/app/app-cache-handler.ts
Labels: :bug: bug, cla-present

#1098 fix: SDA-2559: Delete app cache on Install
  spec/appCacheHandler.spec.ts
  src/app/app-cache-handler.ts
Labels: 9.1.x, :bug: bug, cla-present

#1100 fix: screen-share indicator zoomed in
  src/app/window-handler.ts
Labels: cla-present

#1101 feat: SDA-2390 Modified build script to call signing script on build machine
  scripts/jenkins-win64.bat
Labels: cla-present
