Repository finos/SymphonyElectron, pull requests merged in 2020-07, with the labels that each got.

#1028 feat: add parameter to push the renderer logs inside the SDA-logs
  config/Symphony.config
  docs/features/config-file.md
  src/app/app-menu.ts
  src/app/child-window-handler.ts
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#1029 fix: SDA-2232 Remove extra blank line in installer dialog
  installer/mac/intro.html
Labels: cla-present

#1030 chore: bump version to 9.0.1
  package.json
Labels: cla-present

#1032 fix: SDA-2285 (Update system idle time API and bump version to 9.0.1)
  package.json
  src/app/memory-monitor.ts
Labels: 9.0.1, :bug: bug, blocker, cla-present

#1034 build: SDA-2285 (Bump typescript version to fix 3rd party lint issues)
  package.json
  src/app/window-handler.ts
Labels: 9.0.1, :bug: bug, bump, cla-present

#1033 chore: Bump SDA version to 9.1.0
  package.json
  src/app/window-handler.ts
Labels: bump, cla-present

#1036 fix: SDA-2287 (Only create context bridge when CI is enabled and create new config filed for defining origin)
  config/Symphony.config
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, blocker, cla-present

#1035 fix: SDA-2287 (Only create context bridge when CI is enabled and create new config filed for defining origin)
  config/Symphony.config
  package.json
  src/app/config-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, blocker, cla-present

#1037 fix: SDA-2302 only start main window one time
  src/app/main.ts
Labels: cla-present

#1038 fix: SDA-2301 (Apply contextOriginUrl for pop-out windows as well)
  src/app/child-window-handler.ts
Labels: :bug: bug, cla-present

#1039 fix: SDA-2301 (Apply contextOriginUrl for pop-out windows as well)
  src/app/child-window-handler.ts
Labels: :bug: bug, cla-present

#1040 fix: Enable E2E encryption api in webRTC
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
Labels: cla-present

#1041 chore: Move electron forward to 9.1.1
  package.json
Labels: cla-present
