Repository finos/SymphonyElectron, pull requests merged in 2020-09, with the labels that each got.

#1063 feat: SDA-2392 Running custom scripts in Wix# installer
  installer/win/BuildWixSharpInstaller.bat
  installer/win/Symphony.cs
  installer/win/WixSharpInstaller/Symphony.cs
  scripts/jenkins-win64.bat
Labels: cla-present

#1064 fix: SDA-2279 (Filter out notification windows from desktop capturer)
  src/common/api-interface.ts
  src/renderer/desktop-capturer.ts
  src/renderer/notification.ts
Labels: :bug: bug, cla-present

#1065 feat: SDA-2389 Added custom dialogs
  installer/win/BuildWixSharpInstaller.bat
  installer/win/WixSharpInstaller/Banner.jpg
  installer/win/WixSharpInstaller/ExitDlg.cs
  installer/win/WixSharpInstaller/ExitDlg.designer.cs
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/Tabloid.jpg
  installer/win/WixSharpInstaller/WelcomeDlg.cs
  installer/win/WixSharpInstaller/WelcomeDlg.designer.cs
  installer/win/WixSharpToolset/WixSharp.Lab.dll
  installer/win/WixSharpToolset/WixSharp.Msi.dll
  installer/win/WixSharpToolset/WixSharp.Msi.xml
  installer/win/WixSharpToolset/WixSharp.UI.dll
  installer/win/WixSharpToolset/WixSharp.dll
  installer/win/WixSharpToolset/WixSharp.xml
Labels: cla-present

#1066 fix: SDA-2443 Fixed incorrect file name in edge cases
  src/app/download-handler.ts
  src/app/window-utils.ts
Labels: cla-present

#1067 feat: SDA-2393 Adding/removing registry keys
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1068 feat: SDA-2394 Commandline installation properties
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/WelcomeDlg.cs
Labels: cla-present

#1070 fix: SDA-2467 (Optimize renderer logs and prevent sending renderer to cloud)
  src/app/app-menu.ts
  src/app/child-window-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
  src/common/logger.ts
Labels: :bug: bug, :sparkles: enhancement, cla-present

#1069 fix: SDA-2443 Fixed incorrect file name in edge cases
  src/app/window-utils.ts
Labels: cla-present

#1072 fix: SDA-2418: remove capturing extra system information
  package.json
  src/app/stats.ts
Labels: 6.1.x, :bug: bug

#1075 fix: SDA-2418: remove capturing all stats
  package.json
  src/app/stats.ts
Labels: 9.1.x, :bug: bug

#1073 fix: SDA-2418: remove capturing extra system information
  package.json
  src/app/stats.ts
Labels: 9.0.x, :bug: bug

#1074 fix: SDA-2418: remove capturing all stats
  package.json
  src/app/stats.ts
Labels: :bug: bug

#1071 feat: I18N-978: Add configuration file for Crowdin CLI
  crowdin.yml
Labels: :sparkles: enhancement
