Repository finos/SymphonyElectron, pull requests merged in 2020-05, with the labels that each got.

#983 fix: SDA-2010 (Mac and Linux build scripts)
  scripts/build-linux.sh
  scripts/build-mac.sh
Labels: cla-present

#980 fix: SDA-2008: Invoke screen snippet tool with --no-annotate when running mana
  package.json
  src/app/screen-snippet-handler.ts
Labels: cla-present

#982 feat: SDA-1995: implement download manager for Mana
  spec/downloadHandler.spec.ts
  spec/mainApiHandler.spec.ts
  src/app/download-handler.ts
  src/app/main-api-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/components/download-manager.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present

#985 fix: SDA-2020: Move to Electron 8.2.5 that has fix for enumerateDevices
  package-lock.json
  package.json
Labels: cla-present

#986 fix: SDA-2016: fix simplified installer issues
  installer/mac/background.png
  installer/mac/symphony-mac-packager.pkgproj
  src/app/version-handler.ts
  src/app/window-actions.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#987 feat: SDA-2025: download manager single item api
  src/app/download-handler.ts
  src/app/window-utils.ts
  src/demo/index.html
  src/renderer/components/download-manager.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present

#988 fix: SDA-1970 Changed API call for getting window bounds
  package.json
Labels: cla-present

#989 fix: SDA-2016: fix title bar issue
  package-lock.json
  src/app/window-handler.ts
  src/renderer/styles/welcome.less
Labels: :bug: bug, cla-present

#991 fix: screen share frame stay
  src/app/window-handler.ts
Labels: cla-present

#992 fix: SDA-2056: welcome screen on every install
  installer/win/Symphony-x64.aip
  src/app/main.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#993 fix: SDA-1738 RTC diagnotic start/close screen share quickly
  src/app/window-handler.ts
Labels: cla-present

#994 fix: SDA-2057 (Update few styles to fix the title bar overlap issue)
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, blocker, cla-present, mana

#995 fix: SDA-1970 Correct alignment when window is maximized
  package.json
Labels: cla-present

#996 fix: SDA-2056: welcome dialog issue
  package-lock.json
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/renderer/preload-main.ts
Labels: :bug: bug, cla-present

#997 feat: SDA-1991 (Redesign Notifications)
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
  src/renderer/styles/notification-comp.less
Labels: cla-present, master

#998 feat: SDA-1973 (Expose notifications APIs for mana)
  src/renderer/notification-handler.ts
  src/renderer/preload-main.ts
Labels: cla-present, mana, master

#999 fix: SDA-2080 (Fix a target CSS issue with SFE-Lite & fix title bar button issue in 9.x)
  src/renderer/components/windows-title-bar.tsx
  src/renderer/styles/title-bar.less
Labels: :bug: bug, cla-present, mana, master

#1001 fix: SDA-2080 (Make notification text black for 1.5 and update style template)
  config/titleBarStyles.css
  src/renderer/components/notification-comp.tsx
  src/renderer/styles/notification-comp.less
Labels: cla-present, master

#1002 fix: sda-1843, remove the close button X
  src/app/window-handler.ts
Labels: cla-present

#1003 fix: SDA-2091 (Remove non-serializable content)
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/notification.ts
Labels: :bug: bug, blocker, cla-present

#1005 fix: SDA-2092 (prevent notifications from opening in fullscreen state in MacOS)
  src/renderer/notification.ts
Labels: :bug: bug, cla-present, mana, master

#1004 fix: sda-1971 make the pop-out full screen enable
  spec/childWindowHandle.spec.ts
  src/app/child-window-handler.ts
Labels: cla-present
