Repository finos/SymphonyElectron, pull requests merged in 2020-11, with the labels that each got.

#1102 feat: SDA-2593: new design for a simplified installer flow
  installer/win/WixSharpInstaller/CloseDialog.cs
  installer/win/WixSharpInstaller/CloseDialog.designer.cs
  installer/win/WixSharpInstaller/ExitDialog.cs
  installer/win/WixSharpInstaller/ExitDialog.designer.cs
  installer/win/WixSharpInstaller/MaintenanceDialog.cs
  installer/win/WixSharpInstaller/MaintenanceDialog.designer.cs
  installer/win/WixSharpInstaller/MaintenanceDlg.cs
  installer/win/WixSharpInstaller/MaintenanceDlg.designer.cs
  installer/win/WixSharpInstaller/ProgressDialog.Designer.cs
  installer/win/WixSharpInstaller/ProgressDialog.cs
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/WixSharpInstaller/WelcomeDialog.cs
  installer/win/WixSharpInstaller/WelcomeDialog.designer.cs
Labels: cla-present

#1104 feat: SDA-2170: set context isolation to true by default
  src/app/window-handler.ts
Labels: :shield: security, cla-present

#1105 fix: SDA-2593 Disabled cancel button in progress dialog
  installer/win/WixSharpInstaller/ProgressDialog.Designer.cs
Labels: cla-present

#1103 feat: SDA-2456: add screen annotate tool
  .vscode/launch.json
  .vscode/settings.json
  package.json
  spec/__snapshots__/snippingTool.spec.ts.snap
  spec/snippingTool.spec.ts
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
  src/renderer/assets/snip-draw.svg
  src/renderer/assets/snip-erase.svg
  src/renderer/assets/snip-highlight.svg
  src/renderer/assets/snip-redo.png
  src/renderer/assets/snip-redo.svg
  src/renderer/assets/snip-undo.png
  src/renderer/assets/snip-undo.svg
  src/renderer/components/about-app.tsx
  src/renderer/components/basic-auth.tsx
  src/renderer/components/loading-screen.tsx
  src/renderer/components/notification-comp.tsx
  src/renderer/components/notification-settings.tsx
  src/renderer/components/screen-picker.tsx
  src/renderer/components/screen-sharing-indicator.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/preload-component.ts
  src/renderer/styles/snipping-tool.less
  src/renderer/styles/theme.less
  tslint.json
Labels: cla-present, feature

#1106 fix: SDA-2651 fix a crash on the 1st time uninstallation
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1108 fix: SDA-2657 remove red frame and screen sharing indicator when reloading
  src/app/app-menu.ts
  src/app/window-utils.ts
Labels: cla-present

#1107 feat: SDA-2532 Work on state for annotate and adding color picker
  .vscode/launch.json
  .vscode/tasks.json
  package.json
  spec/__snapshots__/snippingTool.spec.ts.snap
  src/renderer/components/color-picker-pill.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
Labels: cla-present

#1109 chore: SDA-2451: add support to run snyk monitor on build scripts
  scripts/build-linux.sh
  scripts/build-mac.sh
  scripts/build-win32.bat
  scripts/build-win64.bat
Labels: cla-present

#1111 fix: SDA-2651 fix a crash on the 1st time uninstallation
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1110 chore: SDA-2270: change clientVersion to sbeVersion
  spec/aboutApp.spec.ts
  src/renderer/components/about-app.tsx
Labels: cla-present

#1113 feat: SDA-2652 (Add new API to set if running in mana client)
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: cla-present, feature, mana

#1114 fix: SDA-2681 Ensuring correct paths and function for silent install
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1112 feat: SDA-2533 add annotate to screenshot
  spec/__snapshots__/annotateArea.spec.tsx.snap
  spec/__snapshots__/colorPickerPill.spec.tsx.snap
  spec/__snapshots__/snippingTool.spec.ts.snap
  spec/annotateArea.spec.tsx
  spec/colorPickerPill.spec.tsx
  spec/snippingTool.spec.ts
  src/app/window-handler.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/color-picker-pill.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
  tslint.json
Labels: cla-present

#1116 fix: SDA-2651 Using EndSession message to terminate SDA on uninstall
  installer/win/WixSharpInstaller/Symphony.cs
  src/app/window-handler.ts
Labels: cla-present

#1115 fix: SDA-2644 (Fix snippet window resize issue based on screen size)
  spec/__snapshots__/snippingTool.spec.ts.snap
  spec/utils.spec.ts
  src/app/window-handler.ts
  src/common/utils.ts
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
Labels: :bug: bug, cla-present, master

#1117 feat: SDA-2533 Add clear, erase and done functionality.
  spec/__snapshots__/annotateArea.spec.tsx.snap
  spec/__snapshots__/snippingTool.spec.tsx.snap
  spec/annotateArea.spec.tsx
  spec/snippingTool.spec.ts
  spec/snippingTool.spec.tsx
  src/app/screen-snippet-handler.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/color-picker-pill.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
Labels: cla-present

#1119 fix: Sda 2694 2
  package.json
  src/app/window-handler.ts
Labels: cla-present

#1120 fix: setBounds make the application unresponsive and not usable
  src/app/window-handler.ts
Labels: cla-present

#1121 fix: sda-2625 Update translation
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#1122 fix: SDA-2625 Fixed japanese screensnippet translation
  src/locale/ja-JP.json
Labels: cla-present

#1123 feat: SDA-2705 Add possibility for panning
  spec/__snapshots__/annotateArea.spec.tsx.snap
  spec/__snapshots__/snippingTool.spec.tsx.snap
  spec/annotateArea.spec.tsx
  spec/snippingTool.spec.tsx
  src/app/window-handler.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
Labels: cla-present

#1124 feat: SDA-2571, SDA-2721 Add annotate BI and fix window size on windows
  spec/annotateArea.spec.tsx
  spec/snippingTool.spec.tsx
  src/app/analytics-handler.ts
  src/app/window-handler.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/snipping-tool.tsx
Labels: cla-present

#1125 fix: SDA-2694: fix blank screen issues occurred by app cache deletion
  .vscode/launch.json
  package.json
  src/app/config-handler.ts
  src/app/main.ts
  src/app/version-handler.ts
  src/app/window-handler.ts
Labels: 9.1.x, :bug: bug, cla-present

#1126 fix: SDA-2694: fix blank screen on first install
  package.json
  src/app/config-handler.ts
  src/app/main.ts
  src/app/version-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present
