Repository finos/SymphonyElectron, pull requests merged in 2020-08, with the labels that each got.

#1043 fix: SDA-2330 (Update API from querySystemIdleTime to getSystemIdleTime)
  src/app/memory-monitor.ts
Labels: :bug: bug, cla-present

#1042 docs: update documentation for the dev setup
  docs/development/DEV_SETUP.md
Labels: cla-present

#1045 chore: SDA-2345 (Bump SDA version to 9.2.0)
  package.json
Labels: bump, cla-present

#1046 fix: Show client Symphony Classic, Symphony 2.0 or Symphony 2.0 - Daily in…
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/window-handler.ts
  src/renderer/components/about-app.tsx
Labels: :sparkles: enhancement, cla-present

#1047 feat: SDA-2315: add chrome flag for network in process
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
Labels: :sparkles: enhancement, cla-present

#1049 feat: SDA-2315: add chrome flag for network in process
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
Labels: 9.1.x, :sparkles: enhancement, cla-present

#1052 revert: SDA-2315: add chrome flag for network in process
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
Labels: cla-present

#1051 revert: SDA-2315: add chrome flag for network in process
  spec/chromeFlags.spec.ts
  src/app/chrome-flags.ts
Labels: cla-present

#1050 feat: SDA-2352: add new api for restarting SDA
  src/app/app-state-handler.ts
  src/app/main-api-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, cla-present

#1054 fix: address RTC meeting failure
  package.json
Labels: 9.0.x, :bug: bug, cla-present

#1055 fix: address RTC meeting failure
  package.json
Labels: :bug: bug, cla-present, master

#1057 feat: SDA-2386 Added build script to replace the one in jenkins
  scripts/jenkins-win64.bat
Labels: cla-present

#1058 feat: SDA-2386 Generate wix# installer as part of build
  scripts/jenkins-win64.bat
Labels: cla-present

#1060 feat: SDA-2389 Added version number to installer
  installer/win/Symphony.cs
Labels: cla-present

#1059 fix: sda-2268 address security risk pointed out by Snyk
  package.json
Labels: cla-present

#1061 fix: sda-2261 translate enable console logs
  src/locale/en-US.json
  src/locale/en.json
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: cla-present

#1062 fix: sda-2417 enable only RTC insertable streams
  src/app/chrome-flags.ts
Labels: cla-present
