Repository finos/SymphonyElectron, pull requests merged in 2021-02, with the labels that each got.

#1184 Removed unused parameter ChildProcess
  src/app/window-handler.ts
Labels: cla-present

#1186 fix: SDA-2948 (Redesign notification)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present

#1182 fix: SDA-2889 (Send analytic events for toast_closed)
  src/app/analytics-handler.ts
  src/renderer/notification.ts
Labels: :bug: bug, cla-present, mana

#1185 fix: translation of tool tip
  spec/__snapshots__/notificationSettings.spec.ts.snap
  src/renderer/components/notification-settings.tsx
Labels: cla-present

#1187 fix: SDA-2955 (Switch to default HTML input element)
  src/renderer/components/notification-comp.tsx
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present

#1188 SDA-2617: support windows native notifications
  src/app/init.ts
  src/renderer/styles/notification-comp.less
Labels: :sparkles: enhancement, cla-present

#1189 fix: Added error check to detect signing failure
  scripts/build-win64.bat
Labels: cla-present

#1190 Changed timestamp server for advanced installer
  installer/win/Symphony-x64.aip
Labels: cla-present

#1191 Ensure all the exe files are signed for new installer as well
  scripts/build-win64.bat
Labels: cla-present

#1192 SDA-2999 Branching off 9.2.x
  package.json
Labels: cla-present
