Repository finos/SymphonyElectron, pull requests merged in 2021-01, with the labels that each got.

#1165 fix: SDA-2802 (Use emoji as thumbs up button)
  src/renderer/assets/notification-thumbsup.svg
  src/renderer/components/notification-comp.tsx
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, cla-present, master

#1166 fix: SDA-2838: Fix notification settings button for french
  src/app/window-handler.ts
  src/renderer/styles/notification-settings.less
Labels: cla-present

#1167 fix: SDA-2836: If no capture, don't show annotate window
  src/app/screen-snippet-handler.ts
Labels: cla-present

#1168 fix: SDA-2806, SDA-2822 & SDA-2831 (Reposition notifications when on input)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
Labels: :bug: bug, cla-present, master

#1169 fix: We can not just take for the stack of windows, we need to get the mai…
  src/app/window-handler.ts
Labels: cla-present

#1170 feat: SDA-2846, SDA-2847: add support for context origin url in installer
  installer/mac/install_instructions_mac.md
  installer/mac/postinstall.sh
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/install_instructions_win.md
Labels: :sparkles: enhancement, cla-present

#1171 fix: SDA-2852: auto reload main window in case of blank screen
  src/app/child-window-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#1173 fix: SDA-2875: add defense for statSync in logger
  src/common/logger.ts
Labels: :bug: bug, cla-present

#1172 feat: SDA-2824 Set notification position modal darkmode
  spec/__snapshots__/notificationSettings.spec.ts.snap
  spec/mainApiHandler.spec.ts
  spec/notificationSettings.spec.ts
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/components/notification-settings.tsx
  src/renderer/ssf-api.ts
  src/renderer/styles/notification-settings.less
Labels: cla-present

#1174 fix: SDA-2882 (Validate notification background color)
  src/renderer/components/notification-comp.tsx
Labels: :bug: bug, cla-signed, master

#1175 fix: SDA-2857 (Increase the notification height to make more space for message content)
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification.ts
  src/renderer/styles/notification-comp.less
Labels: :sparkles: enhancement, cla-present, master

#1176 fix: sda-2916 got several listeners to screen-source-select, remove all listeners w…
  src/app/window-handler.ts
Labels: cla-present

#1177 fix: Left align the text
  src/renderer/styles/notification-settings.less
Labels: cla-present

#1178 fix: SDA-2934: Upgrade electron to 9.4.1
  package.json
Labels: :shield: security, cla-present

#1179 fix: SDA-2912 Split registry cleaning actions to elevated/non-elevated
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1180 fix: SDA-2931 Set Symphony as the publisher name
  installer/win/WixSharpInstaller/Symphony.cs
Labels: cla-present

#1183 SDA-2887: analytics for SDA crashes
  spec/__mocks__/electron.ts
  src/app/analytics-handler.ts
  src/app/child-window-handler.ts
  src/app/crash-handler.ts
  src/app/init.ts
  src/app/reports-handler.ts
  src/app/window-handler.ts
Labels: cla-present, feature
