Repository finos/SymphonyElectron, pull requests merged in 2021-03, with the labels that each got.

#1193 SDA-2977: UBS: Inconsistent 'Copy Email Address' output on MessageML
  src/app/child-window-handler.ts
  src/renderer/notification.ts
Labels: cla-present

#1195 fix: SDA-2977: fix copying email address on context menu
  package.json
Labels: cla-present

#1197 fix: SDA-3030: enable remote module explicitly
  scripts/build-win64.bat
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#1198 fix: SDA-3030: enable remote module explicitly
  package.json
  scripts/build-win64.bat
  src/app/window-handler.ts
Labels: :bug: bug, cla-present

#1201 fix: update electron spellchecker
  package.json
Labels: cla-present

#1202 fix: persist sso
  src/app/window-handler.ts
Labels: cla-present

#1203 Add VS Code launch config for st2
  .vscode/launch.json
Labels: cla-present

#1205 SDA-3039: whitelist symphony protocol for new windows
  src/app/child-window-handler.ts
Labels: :sparkles: enhancement, cla-present

#1207 SDA-3039: force opening external app for symphony and mailto
  src/app/window-actions.ts
Labels: :sparkles: enhancement, cla-present

#1206 fix: sda-2992 safe guard if user config is missing
  src/app/window-handler.ts
Labels: cla-present
