Repository finos/SymphonyElectron, pull requests merged in 2022-11, with the labels that each got.

#1528 New translations in main
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: localization

#1533 New translations in main
  src/locale/fr-FR.json
  src/locale/fr.json
Labels: localization

#1536 SDA-3931: Screenshot tool improvement - Phase 1
  spec/__snapshots__/menu-button.spec.tsx.snap
  spec/__snapshots__/snippingTool.spec.tsx.snap
  spec/menu-button.spec.tsx
  spec/snippingTool.spec.tsx
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/common/ipcEvent.ts
  src/locale/en-US.json
  src/locale/en.json
  src/renderer/assets/single-chevron-down.svg
  src/renderer/components/menu-button.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/styles/snipping-tool.less
  src/renderer/styles/theme.less
Labels: 20.0.0

#1547 SDA-3958: Fix crash app on close
  src/app/window-handler.ts
Labels: 20.0.0

#1550 SDA-3959: Fixing some UI css bugs
  spec/__snapshots__/menu-button.spec.tsx.snap
  src/renderer/components/menu-button.tsx
  src/renderer/styles/snipping-tool.less
  src/renderer/styles/theme.less
Labels: 20.0.0

#1558 New translations in main
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: localization

#1554 SDA-3933: Add api to hide SDA
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/screen-snippet-handler.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: 21.0.0
