Repository finos/SymphonyElectron, pull requests merged in 2022-02, with the labels that each got.

#1335 Revert "SDA-3565 - Allow C2 / extensions to determine the presence of Citrix media redirection (#1331)"
  package-lock.json
  package.json
  spec/citrixHandler.spec.ts
  spec/mainApiHandler.spec.ts
  src/app/citrix-handler.ts
  src/app/main-api-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: 14.0.x

#1336 SDA-3554 (Add accelerator to export logs)
  src/app/app-menu.ts
  src/app/reports-handler.ts
  src/app/window-handler.ts
Labels: :sparkles: enhancement

#1337 SDA-3574 (Fix the condition to validate undefined)
  src/app/app-state-handler.ts
Labels: :bug: bug

#1339 SDA-3565 Citrix media redirection presence update
  installer/win/WixSharpInstaller/Symphony.cs
  package-lock.json
  package.json
  spec/citrixHandler.spec.ts
  src/app/citrix-handler.ts
Labels: 14.0.x

#1340 SDA-3565 Citrix media redirection status API endpoint
  src/app/citrix-handler.ts
  src/app/main-api-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: 14.0.x

#1341 SDA-3577 (Remove isNodeEnv usage)
  src/app/init.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/env.ts
  src/renderer/notification.ts
Labels: feature, 14.0.x

#1342 Disabling auto-update service and helper
  installer/win/WixSharpInstaller/Symphony.cs
  scripts/build-win64.bat
  src/app/main-api-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/app-bridge.ts
  src/renderer/ssf-api.ts
Labels: 14.0.x

#1343 SDA-3580 Logging cleanup
  src/app/main-api-handler.ts
Labels: 14.0.x

#1344 Enriched renderer crash logs
  src/app/window-handler.ts
Labels: 14.0.x

#1346 SDA-3583 (Upgrade SDA version to 14.1.0)
  package.json
Labels: 14.1.x

#1349 SDA-3525 Removing reply tooltip for notifications
  src/renderer/components/notification-comp.tsx
Labels: 14.1.x

#1348 SDA-3532 Snipping tool should remain on the top on Windows and MacOS
  src/app/window-handler.ts
Labels: 14.1.x

#1351 SDA-3532 Snipping tool should remain on the top on Windows and MacOS …
  src/app/window-handler.ts
Labels: 14.0.x

#1357 SDA-3593 Citrix redirection registry key update
  .github/workflows/ci.yml
  src/app/citrix-handler.ts
Labels: :bug: bug

#1350 SDA-3525 Removing reply tooltip for notifications (#1349)
  src/renderer/components/notification-comp.tsx
Labels: 14.0.x

#1360 SDA-3596 (Set the bounds for newly created child window)
  src/app/child-window-handler.ts
Labels: :bug: bug, 14.0.x

#1359 SDA-3596 (Set the bounds for newly created child window)
  src/app/child-window-handler.ts
Labels: :bug: bug, 14.1.x
