Repository finos/SymphonyElectron, pull requests merged in 2022-10, with the labels that each got.

#1513 SDA-3913 (Set up first time launch for auto updated version)
  build/installer.nsh
  src/app/config-handler.ts
  src/app/main-api-handler.ts
Labels: :bug: bug, master

#1514 SDA-3913 (Set up first time launch for auto updated version)
  build/installer.nsh
  src/app/config-handler.ts
  src/app/main-api-handler.ts
Labels: :bug: bug, 19.0.0

#1517 SDA-3892_Crowdin: Remove few files for Crowdin Test
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: 20.0.0

#1518 New translations in main
  src/locale/fr-FR.json
  src/locale/fr.json
  src/locale/ja-JP.json
  src/locale/ja.json
Labels: localization

#1519 SDA-3901 (Add new implementation for welcome screen)
  config/Symphony.config
  package-lock.json
  spec/__mocks__/electron.ts
  spec/__snapshots__/welcome.spec.ts.snap
  spec/protocolHandler.spec.ts
  spec/welcome.spec.ts
  src/app/config-handler.ts
  src/app/main-api-handler.ts
  src/app/protocol-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/locale/en-US.json
  src/locale/en.json
  src/renderer/assets/welcome-symphony-logo.svg
  src/renderer/components/welcome.tsx
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/react-window.html
  src/renderer/styles/theme.less
  src/renderer/styles/welcome.less
Labels: 20.0.0
