Repository finos/SymphonyElectron, pull requests merged in 2022-04, with the labels that each got.

#1367 SDA-3606 Removing SSO checkbox in Welcome screen
  spec/__snapshots__/welcome.spec.ts.snap
  spec/welcome.spec.ts
  src/renderer/components/welcome.tsx
  src/renderer/styles/welcome.less
Labels: 14.1.x

#1369 SDA-3219 Disabling aux click
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/renderer/notification.ts
Labels: 14.1.x

#1372 Bugfix/rtc 17.0.x
  package-lock.json
  package.json
  spec/hwndHandler.spec.ts
  src/app/hwnd-handler.ts
  src/app/main-api-handler.ts
Labels: 17.0.0

#1373 SDA-3626 Electron 17.3.0 upgrade (#1371)
  package-lock.json
  package.json
  src/app/main-api-handler.ts
  src/app/window-handler.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/renderer/desktop-capturer.ts
Labels: 17.0.0

#1382 SDA-3637 (Move away from third party electron-spellchecker module)
  package-lock.json
  package.json
  src/app/context-menu-builder.ts
  src/app/main-api-handler.ts
  src/app/spell-check-handler.ts
  src/common/api-interface.ts
  src/renderer/preload-main.ts
Labels: :sparkles: enhancement, feature, 17.0.0

#1381 SDA-3606 Removing SSO checkbox in Welcome screen (#1367)
  spec/__snapshots__/welcome.spec.ts.snap
  spec/welcome.spec.ts
  src/renderer/components/welcome.tsx
  src/renderer/styles/welcome.less
Labels: 17.0.0

#1395 SDA-3662 (Fix window will navigate issue on main webContents)
  package-lock.json
  src/app/window-utils.ts
Labels: :bug: bug, 17.0.0

#1396 SDA-3662 (Fix window will navigate issue on main webContents)
  src/app/window-utils.ts
Labels: :bug: bug, 17.0.0

#1397 SDA-3673 (Publish main events only for events from main window)
  src/app/window-actions.ts
Labels: :bug: bug, master

#1398 SDA-3673 (Publish main events only for events from main window)
  src/app/window-actions.ts
Labels: :bug: bug, blocker, 17.0.0
