Repository finos/SymphonyElectron, pull requests merged in 2022-01, with the labels that each got.

#1312 SDA-3530 (Clear snippet window reference after close)
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/app/window-handler.ts
Labels: :bug: bug

#1313 SDA-3440 (Disable Zoom for notification windows)
  src/app/window-utils.ts
Labels: :bug: bug

#1314 SDA-3489 (Bump electron spellcheck version to 2.3.3)
  package.json
Labels: :sparkles: enhancement

#1320 SDA-3489 (Update electron spellchecker repo url)
  package.json
Labels: bump

#1311 SDA-3534 Centering SDA snipping tool
  src/app/window-handler.ts
Labels: :bug: bug

#1321 SDA-3516 (Focus main webContents on "second-instance" event)
  src/app/main.ts
Labels: :bug: bug, master, 14.0.x

#1323 SDA-3489 (bump electron spellchecker version to 2.3.4)
  package-lock.json
  package.json
Labels: bump

#1324 SDA-3534 Snipping tool height shouldn't be greater than screen width and height
  src/app/window-handler.ts
Labels: 14.0.x

#1325 SDA-3534 Snipping tool width shouldn't be greater than screen width and height
  src/app/window-handler.ts
Labels: 14.0.x

#1326 SDA-3516 (Refocus to main webContents when title bar action buttons are clicked)
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, 14.0.x

#1327 SDA-3544 (Reset the width and height of the inactive notification to the default size)
  src/renderer/notification.ts
Labels: :bug: bug, 14.0.x

#1333 SDA-3568 Bump spellchecker version to 2.3.6
  package-lock.json
  package.json
Labels: 14.0.x
