Repository finos/SymphonyElectron, pull requests merged in 2022-06, with the labels that each got.

#1436 SDA-3731 shell-path upgrade
  package-lock.json
  package.json
  src/app/main.ts
Labels: :no_entry: do-not-merge

#1437 SDA-3733 (Upgrade electron version to 19)
  .github/workflows/ci.yml
  .travis.yml
  installer/win/WixSharpInstaller/Symphony.cs
  package-lock.json
  package.json
  scripts/build-mac.sh
  scripts/build-win32.bat
  scripts/build-win64.bat
  spec/__mocks__/electron.ts
  spec/appMenu.spec.ts
  spec/childWindowHandle.spec.ts
  spec/config.spec.ts
  spec/dialogHandler.spec.ts
  spec/mainApiHandler.spec.ts
  src/app/config-handler.ts
  src/app/main-api-handler.ts
  travis.yml
Labels: bump, master, 19.0.0

#1445 SDA-3733 (Include everything from node_modules)
  installer/win/WixSharpInstaller/Symphony.cs
  package-lock.json
  package.json
  src/app/init.ts
  tsconfig.json
Labels: :bug: bug, :sparkles: enhancement, quality checks, 19.0.0
