Repository finos/SymphonyElectron, pull requests merged in 2023-12, with the labels that each got.

#2024 SDA-4256 (Apply hide fullscreen if minimize on close enabled)
  src/app/window-handler.ts
Labels: :bug: bug, 24.1.0

#2025 SDA-4077 (Add support for persisting client logs after reload)
  src/app/main-api-handler.ts
  src/app/reports-handler.ts
  src/common/api-interface.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
Labels: :sparkles: enhancement, master, feature, 24.1.0

#2029 SDA-4406 -(Auto-update silent download)
  src/app/auto-update-handler.ts
Labels: master, feature, 24.1.0

#2019 SDA-4271: SIG-Back button causes SDA 23.4 to present a blank screen
  src/app/window-handler.ts
  src/renderer/preload-main.ts
Labels: 23.4.1

#2031 SDA-4417 - Optimize focus event listener
  src/app/window-handler.ts
Labels: :bug: bug, 24.1.0

#2033 SDA-4419 (Fix maximize and unmaximize button height)
  spec/__snapshots__/windowsTitleBar.spec.ts.snap
  src/renderer/components/windows-title-bar.tsx
Labels: :bug: bug, 24.1.0
