Repository finos/SymphonyElectron, pull requests merged in 2023-07, with the labels that each got.

#1892 SDA-4223: Add new option to overwrite auto-update pmp
  installer/mac/postinstall.sh
  installer/win/WixSharpInstaller/Symphony.cs
  installer/win/install_instructions_win.md
  src/app/app-menu.ts
  src/app/config-handler.ts
  src/app/window-utils.ts
Labels: 23.8.0

#1891 SDA-4220 (Implement API for call notification)
  spec/__mocks__/electron.ts
  spec/callNotification.spec.ts
  spec/mainApiHandler.spec.ts
  src/app/main-api-handler.ts
  src/app/notifications/call-notification.ts
  src/app/window-handler.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/assets/call-icon.svg
  src/renderer/call-notification-helper.ts
  src/renderer/components/call-notification.tsx
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-handler.ts
  src/renderer/notification-theme.ts
  src/renderer/notification.ts
  src/renderer/preload-component.ts
  src/renderer/preload-main.ts
  src/renderer/ssf-api.ts
  src/renderer/styles/call-notification.less
  src/renderer/styles/theme.less
Labels: feature, 23.8.0

#1900 SDA-4231 (Fix button width for macOS)
  src/renderer/components/call-notification.tsx
  src/renderer/styles/call-notification.less
Labels: :bug: bug, 23.8.0

#1902 SDA-4233 & SDA-4232 (Fix EXT alignment and closing exiting window issue)
  src/app/notifications/call-notification.ts
  src/renderer/styles/call-notification.less
Labels: :bug: bug, 23.8.0

#1905 SDA-4241 (Move click handler on to button)
  src/renderer/components/call-notification.tsx
Labels: :bug: bug, 23.8.0

#1910 SDA-4243 (Fix issue with lower-left calculation)
  src/renderer/notification-handler.ts
Labels: :bug: bug, 23.8.0, backport

#1909 SDA-4243 (Fix issue with lower-left calculation)
  src/renderer/notification-handler.ts
Labels: :bug: bug, master

#1911 SDA-4241 (Move click handler on to button)
  src/renderer/components/call-notification.tsx
Labels: :bug: bug, 23.8.0, backport

#1904 SDA-4186 (Add support to update user POD settings)
  spec/aboutApp.spec.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
  src/renderer/components/about-app.tsx
  src/renderer/styles/about-app.less
Labels: feature, localization, 23.11.0

#1908 SDA-4219 (Change logic to use minimize/restore instead of hide/show)
  src/app/stores/window-store.ts
Labels: :bug: bug, master

#1918 SDA-4247 (Update user config once on before-quit)
  spec/appCacheHandler.spec.ts
  src/app/app-cache-handler.ts
  src/app/app-state-handler.ts
  src/app/config-handler.ts
  src/app/dialog-handler.ts
  src/app/window-handler.ts
Labels: 23.11.0
