Repository finos/SymphonyElectron, pull requests merged in 2023-08, with the labels that each got.

#1921 SDA-4234: Support Tel Protocol on loading _blank
  src/app/child-window-handler.ts
  src/app/protocol-handler.ts
Labels: master

#1928 SDA-4253 (Handle key down on pod input - AboutApp)
  src/renderer/components/about-app.tsx
Labels: 23.11.0

#1932 SDA-4251 (Workaround to fix always on top issue)
  src/app/window-handler.ts
Labels: :bug: bug, 23.11.0

#1933 SDA-4265 (Handle uncaught exceptions)
  src/app/config-handler.ts
  src/app/window-handler.ts
  src/locale/en-US.json
  src/locale/en.json
Labels: :bug: bug, 23.11.0

#1941 SDA-4266 (Log SDA version info)
  src/app/stats.ts
Labels: quality checks, 23.11.0

#1931 SDA-4235 (Refactor auto update handler)
  src/app/auto-update-handler.ts
Labels: 23.11.0

#1944 SDA-4267 (Remove config file if the file is empty)
  src/app/app-menu.ts
  src/app/config-handler.ts
Labels: :bug: bug, :sparkles: enhancement, 23.11.0
