Repository finos/SymphonyElectron, pull requests merged in 2023-10, with the labels that each got.

#1966 SDA-4332 & SDA-4359 (Limit toast notification to prevent overlying of call notification)
  src/app/auto-update-handler.ts
  src/renderer/notification-handler.ts
Labels: :bug: bug, 23.11.0

#1969 SDA-4359 & SDA-4291 (Refactor BI & send in memory session analytic events)
  package-lock.json
  spec/snippingTool.spec.tsx
  src/app/app-menu.ts
  src/app/auto-update-handler.ts
  src/app/bi/analytics-handler.ts
  src/app/bi/auto-update-analytics.ts
  src/app/config-handler.ts
  src/app/crash-handler.ts
  src/app/main-api-handler.ts
  src/app/memory-monitor.ts
  src/app/screen-snippet-handler.ts
  src/app/stats.ts
  src/app/window-handler.ts
  src/renderer/app-bridge.ts
  src/renderer/components/annotate-area.tsx
  src/renderer/components/snipping-tool.tsx
  src/renderer/notification.ts
Labels: :bug: bug, 23.11.0

#1976 SDA-4361 (Queue & send analytics data once client registers the func)
  src/app/bi/analytics-handler.ts
  src/app/bi/auto-update-analytics.ts
  src/app/config-handler.ts
  src/app/main-api-handler.ts
  src/app/stats.ts
  src/app/window-handler.ts
  src/renderer/ssf-api.ts
Labels: :bug: bug, 23.11.0

#1977 SDA-4235 (Add missing check for betaAutoUpdateChannelEnabled)
  src/app/auto-update-handler.ts
Labels: 23.11.0

#1979 SDA-4290 (Update check to validate object length)
  src/app/auto-update-handler.ts
Labels: 23.11.0

#1981 SDA-4291 (Add delay for sending analytics events)
  src/common/utils.ts
  src/renderer/ssf-api.ts
Labels: :bug: bug, 23.11.0

#1982 SDA-4372 (Always retrieve latest registry channel)
  src/app/auto-update-handler.ts
Labels: 23.11.0

#1984 SDA-4372 (Always retrieve latest registry channel)
  src/app/auto-update-handler.ts
Labels: backport, 23.11.0

#1986 SDA-4291 (Add delay for sending analytics events)
  src/common/utils.ts
  src/renderer/ssf-api.ts
Labels: backport, 23.11.0

#1994 SDA-4374-4373_23.11.x: Backports
  src/app/config-handler.ts
  src/app/local-menu-shortcuts.ts
  src/app/window-handler.ts
Labels: backport, 23.11.0

#1996 SDA-4378 (Rearrange close event)
  src/renderer/components/about-app.tsx
Labels: :bug: bug, 23.11.0

#1997 SDA-4378 (Rearrange close event)
  src/renderer/components/about-app.tsx
Labels: backport, 23.11.0
