Repository finos/SymphonyElectron, pull requests merged in 2024-03, with the labels that each got.

#2106 [Dev] SDA-4496 (Fix dev env issue by setting default values in .plist file)
  src/app/init.ts
Labels: master

#2110 SDA-4481_24.4: Add Fix to image cannot be copied
  src/app/context-menu-builder.ts
Labels: 24.4.0

#2107 SDA-4494 (Force welcome screen in user config url is not configured correctly) [bug]
  src/app/window-handler.ts
Labels: :bug: bug, 24.5.0

#2111 SDA-4496 (setUserDefault only for macOS)
  src/app/init.ts
Labels: master, 24.5.0

#2112 SDA-3856 (Remove config version from user config)
  src/app/config-handler.ts
Labels: :bug: bug, master, 24.5.0

#2115 SDA-4507 (Add validation for copying old global config file)
  spec/plistHandler.spec.ts
  src/app/config-handler.ts
  src/app/plist-handler.ts
Labels: :bug: bug, master, 24.5.0

#2116 SDA-4507 (Add validation for copying old global config file)
  spec/plistHandler.spec.ts
  src/app/config-handler.ts
  src/app/plist-handler.ts
  src/app/window-handler.ts
Labels: :bug: bug, backport, 24.4.0

#2114 SDA-4503 (Add federated green theme for notifications 🟢)
  src/app/init.ts
  src/common/api-interface.ts
  src/demo/index.html
  src/renderer/components/call-notification.tsx
  src/renderer/components/notification-comp.tsx
  src/renderer/notification-theme.ts
  src/renderer/notification.ts
  src/renderer/styles/call-notification.less
  src/renderer/styles/notification-comp.less
  src/renderer/styles/notifications-animations.less
  src/renderer/styles/variables.less
Labels: master, feature, 24.5.0
