Repository finos/SymphonyElectron, pull requests merged in 2024-04, with the labels that each got.

#2122 SDA-4197 - Use correct variable to clear interval
  src/app/window-utils.ts
Labels: :bug: bug, master, 24.6.0

#2109 SDA-4481: Add Fix to image cannot be copied
  src/app/context-menu-builder.ts
Labels: 24.4.0

#2120 SDA-4506 - Apply Zoom for notification window
  src/app/notifications/notification-helper.ts
  src/app/window-utils.ts
  src/common/api-interface.ts
  src/renderer/call-notification-helper.ts
  src/renderer/components/call-notification.tsx
  src/renderer/components/notification-comp.tsx
  src/renderer/notification.ts
Labels: master, feature, 24.6.0

#2124 SDA-4197 (Use correct variable to clear interval)
  src/app/window-utils.ts
Labels: :bug: bug, backport, 24.5.0

#2125 SDA-4528: Minimize Windows wont disappear on capture with SDA Hidden
  src/app/stores/window-store.ts
Labels: 24.5.0

#2128 SDA-4489 (Force auto update)
  package-lock.json
  src/app/auto-update-handler.ts
  src/app/main.ts
Labels: master, feature, 24.5.0

#2129 SDA-4489 (Fix import)
  package.json
  src/app/auto-update-handler.ts
Labels: :bug: bug, feature, 24.5.0

#2131 SDA-4528: Minimize Windows wont disappear on capture with SDA Hidden
  src/app/stores/window-store.ts
Labels: 24.5.0

#2134 SDA-4552 (Change signing tool for .msi)
  scripts/build-win64.bat
Labels: :bug: bug, 24.5.0

#2135 SDA-4552 (Changing sign tool)
  scripts/build-win64.bat
Labels: :bug: bug, backport, 24.5.0

#2132 SDA-4489 (Invoke check for update & download before force install)
  src/app/auto-update-handler.ts
Labels: master, feature, 24.6.0

#2137 SDA-4489 (Fix issue related to different env)
  src/app/auto-update-handler.ts
  src/app/main.ts
Labels: :bug: bug, 24.6.0

#2138 SDA-4553 (Apply client zoom for toast notifications)
  src/app/main-api-handler.ts
  src/app/window-utils.ts
  src/renderer/styles/call-notification.less
  src/renderer/styles/notification-comp.less
Labels: :bug: bug, master, 24.6.0

#2136 SDA-4501 (Initialize new data if the user config is unable to parse)
  src/app/config-handler.ts
Labels: :bug: bug, master, 24.6.0
