Repository finos/SymphonyElectron, pull requests merged in 2024-01, with the labels that each got.

#2047 SDA-4433: Clicking on the Close button in edit pod URL screen does not close the About
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/renderer/components/about-app.tsx
Labels: 24.1.0

#2050 SDA-4427: Add fix to case of close and capture with sym hidden
  src/app/screen-snippet-handler.ts
  src/app/stores/window-store.ts
Labels: 24.1.0

#2051 SDA-4434_4436: Update Fr/Jp text and Update PodURL Change
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/renderer/components/about-app.tsx
  src/renderer/styles/about-app.less
Labels: 24.1.0

#2052 SDA-4433 (Revert SDA-4418)
  src/app/window-utils.ts
Labels: :bug: bug, 24.1.0

#2053 SDA-4427_24.1: Add fix to case of close and capture with sym hidden
  src/app/screen-snippet-handler.ts
  src/app/stores/window-store.ts
Labels: 24.1.0

#2054 SDA-4434_4436_24.1: Update Fr/Jp text and Update PodURL Change
  spec/__snapshots__/aboutApp.spec.ts.snap
  src/renderer/components/about-app.tsx
  src/renderer/styles/about-app.less
Labels: 24.1.0

#2057 SDA-4435 (Revert SDA-4418)
  src/app/window-utils.ts
Labels: :bug: bug, master

#2060 SDA-4412: Update Win Installer
  installer/win/install_instructions_win.md
Labels: 24.1.0

#2061 SDA-4412_24.1: Update Win Installer
  installer/win/install_instructions_win.md
Labels: 24.1.0

#2063 SDA-4443_4444: Adding A11Y to Close and Prevent enter while pod is disabled
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/aboutApp.spec.ts
  src/renderer/components/about-app.tsx
Labels: 24.1.0

#2071 SDA-4443_4444: Adding A11Y to Close and Prevent enter while pod is disabled
  spec/__snapshots__/aboutApp.spec.ts.snap
  spec/aboutApp.spec.ts
  src/renderer/components/about-app.tsx
Labels: backport main, 24.1.0

#2072 SDA-4441: Restore focus on main after closing sub Windows
  src/app/window-handler.ts
Labels: 24.1.0

#2070 SDA-3833 (Update isDevEnv check)
  .run/Demo (Build & Run).run.xml
  package.json
  spec/config.spec.ts
  src/common/env.ts
Labels: :sparkles: enhancement, master, 24.2.0
