Repository finos/SymphonyElectron, pull requests merged in 2024-05, with the labels that each got.

#2140 Revert SDA-4489
  package-lock.json
  package.json
  src/app/auto-update-handler.ts
  src/app/main.ts
Labels: master

#2143 SDA-4561 (Bump SDA and Electron version)
  package-lock.json
  package.json
Labels: bump, 24.7.0

#2144 SDA-4489 (Force auto update) [Feature]
  src/app/auto-update-handler.ts
  src/app/main.ts
Labels: :sparkles: enhancement, master, feature

#2147 SDA-4563 (Ignore changing zoom if focused window is notification window) [Bug]
  src/app/window-utils.ts
Labels: :bug: bug, backport, 24.6.0

#2146 SDA-4563 (Ignore changing zoom if focused window is notification window) [Bug]
  src/app/window-utils.ts
Labels: master, 24.7.0

#2148 SDA-4563 (Ignore changing zoom if focused window is about Symphony)
  src/app/window-utils.ts
Labels: :bug: bug, master

#2149 SDA-4563 (Ignore changing zoom if focused window is about Symphony) [Bug]
  src/app/window-utils.ts
Labels: :bug: bug, backport, 24.6.0

#2150 SDA-4544 (only load dev tool extension on dev env)
  src/app/main.ts
Labels: :bug: bug, master

#2142 SDA-4514: NSIS Migration
  build/installer.nsh
Labels: 24.7.0

#2151 SDA-4562 (Uninstall nsis installer registry entries)
  installer/win/WixSharpInstaller/Symphony.cs
Labels: :bug: bug, master, 24.7.0

#2152 SDA-4489 (Use correct url to validate)
  src/app/auto-update-handler.ts
Labels: :bug: bug, master, 24.7.0

#2155 SDA-4489 (Just use version) [bug]
  src/app/auto-update-handler.ts
Labels: :bug: bug, master, 24.7.0
